import type { BlogArticle } from "../types";
import {
  p,
  h2,
  h3,
  ul,
  ol,
  callout,
  img,
  cta,
  linkCard,
  blogFeatured,
  blogInline,
  estimateReadTime,
} from "../helpers";

const slug = "landing-page-captacao-leads-elementos";

const sections = [
  p("Empresa investe R$ 8.000/mês em Google Ads e direciona tráfego para homepage. Taxa de conversão: 1,1%. Mesma empresa cria landing page dedicada com 12 elementos estruturados. Taxa de conversão: 4,6%. Mesmo tráfego, 4x mais leads — sem aumentar um centavo em mídia."),
  p("Landing page de captação não é página bonita — é máquina de conversão com arquitetura deliberada. Cada elemento existe para reduzir fricção, construir confiança ou impulsionar ação. Omitir qualquer um deles custa leads silenciosamente."),
  img(
    blogInline(slug, 0),
    "Checklist dos 12 elementos essenciais de landing page para captação de leads",
    "Anatomia de landing page de alta conversão para campanhas pagas.",
  ),
  h2("Por que landing page dedicada — sempre"),
  p("Homepage serve múltiplos públicos com múltiplos objetivos: branding, navegação, SEO, conteúdo. Visitante de campanha paga precisa de uma coisa: converter. Landing page elimina distrações, alinha mensagem ao anúncio e concentra visitante em um único CTA. Benchmark Raise One: LPs dedicadas convertem 3–5x mais que homepage em tráfego pago."),
  linkCard({
    label: "Landing page vs site institucional",
    href: "/blog/landing-page-vs-site-institucional",
    type: "article",
    description: "Quando usar cada formato e por que misturar custa caro em campanhas pagas.",
  }),
  h2("Checklist: 12 elementos de landing page de alta conversão"),
  p("Use este checklist para auditar landing pages existentes ou construir novas. Cada elemento inclui critério de qualidade — não basta existir, precisa funcionar."),
  h3("1. Headline alinhada ao anúncio"),
  p("Primeira coisa que visitante lê deve espelhar promessa do anúncio que clicou. Desalinhamento gera bounce imediato. Headline clara, específica, com benefício principal. Exemplo: anúncio 'Botox a partir de R$ 599' → headline 'Botox com especialista CRM — a partir de R$ 599'. Teste A/B de headlines é o teste de maior impacto."),
  h3("2. Subheadline com proposta de valor"),
  p("Complementa headline com contexto: para quem, como funciona, diferencial. Uma ou duas frases. Não repete headline — expande. 'Avaliação gratuita · Resultado em 7 dias · Unidade Moema'."),
  h3("3. Hero visual relevante"),
  p("Imagem ou vídeo que reforça oferta — não stock photo genérica. Clínica: foto real do consultório ou profissional. Imobiliária: render ou foto do empreendimento. Educação: campus ou aluno em contexto. Vídeo curto (< 60s) aumenta engajamento em serviços complexos."),
  h3("4. CTA primário acima da dobra"),
  p("Botão visível sem scroll: 'Agendar avaliação', 'Solicitar proposta', 'Quero me matricular'. Cor contrastante, texto orientado a ação — nunca 'Enviar' ou 'Clique aqui'. Repita CTA após cada bloco de conteúdo relevante."),
  h3("5. Formulário enxuto e progressivo"),
  p("Peça apenas o essencial no primeiro contato: nome, telefone, e-mail. Campos extras reduzem conversão 10–30% por campo adicional. Qualificação profunda vem no follow-up — não no formulário. Considere formulário em duas etapas para serviços complexos: etapa 1 captura contato, etapa 2 qualifica."),
  h3("6. Prova social credível"),
  p("Depoimentos com nome, foto e contexto. Avaliações Google ou Reclame Aqui integradas. Logos de clientes ou parceiros. Números concretos: '+2.400 alunos formados', '4,9 estrelas em 180 avaliações'. Prova social genérica ('Clientes satisfeitos') não converte."),
  h3("7. Benefícios — não features"),
  p("Lista de o que visitante ganha, não o que você oferece tecnicamente. Errado: 'CRM integrado'. Certo: 'Seu consultor responde em menos de 15 minutos'. Traduza cada feature em outcome para o visitante."),
  h3("8. Seção de objeções"),
  p("Antecipe dúvidas: preço, prazo, garantia, comparação com concorrência. FAQ compacto ou blocos 'Por que escolher [marca]'. Objeção não respondida vira abandono silencioso."),
  h3("9. Urgência ou escassez autêntica"),
  p("Vagas limitadas, bolsas até data X, unidades restantes — apenas se verdadeiro. Urgência falsa destrói confiança. Countdown real para campanha sazonal funciona; countdown fake permanente não."),
  h3("10. Trust signals"),
  p("Selos, certificações, associações profissionais, política de privacidade visível, HTTPS, LGPD compliance. Para saúde e educação, credenciais regulatórias (CRM, MEC) são obrigatórias. Trust bar abaixo do formulário reduz hesitação."),
  h3("11. WhatsApp ou chat como alternativa"),
  p("Parte significativa de visitantes prefere mensagem a formulário. Botão WhatsApp flutuante ou inline com mensagem pré-preenchida do serviço de interesse. Rastreie cliques WhatsApp como conversão secundária no Google Ads."),
  h3("12. Mobile-first e velocidade"),
  p("60%+ do tráfego pago vem de mobile. Layout responsivo, botões tocáveis, formulário simplificado. PageSpeed acima de 80 no mobile — cada segundo extra de carregamento reduz conversão ~7%. Comprima imagens, lazy load, minimize scripts."),
  callout(
    "Landing page com 12 elementos mal executados perde para LP com 8 elementos excelentes. Qualidade de execução importa tanto quanto presença no checklist.",
    "Dica Raise One",
  ),
  ol([
    "Headline alinhada ao anúncio",
    "Subheadline com proposta de valor",
    "Hero visual relevante",
    "CTA primário acima da dobra",
    "Formulário enxuto",
    "Prova social credível",
    "Benefícios orientados ao visitante",
    "Seção de objeções / FAQ",
    "Urgência autêntica",
    "Trust signals",
    "WhatsApp ou chat alternativo",
    "Mobile-first e velocidade",
  ]),
  h2("Estrutura de página recomendada"),
  p("Ordem vertical que guia visitante do interesse à ação:"),
  ul([
    "Hero: headline + subheadline + CTA + formulário ou botão",
    "Prova social rápida: logos ou avaliação",
    "Benefícios: 3–5 blocos com ícone e texto curto",
    "Como funciona: 3 passos simples",
    "Depoimentos: 2–3 cases reais",
    "FAQ / objeções: 4–6 perguntas",
    "CTA final repetido com urgência se aplicável",
    "Footer mínimo: privacidade, contato, endereço",
  ]),
  p("Evite menu de navegação completo — links de fuga reduzem conversão. Logo clicável pode ir para site principal, mas minimize distrações."),
  h2("Tracking e otimização contínua"),
  p("Landing page é produto vivo, não projeto fechado. Configure:"),
  ul([
    "Conversão primária: envio de formulário",
    "Conversão secundária: clique WhatsApp",
    "Heatmap e gravação de sessão (Hotjar, Clarity) para identificar abandono",
    "Teste A/B de headline, CTA e formulário — um elemento por vez",
    "GCLID em hidden field para atribuição offline",
  ]),
  linkCard({
    label: "Integrar Google Ads, CRM e WhatsApp",
    href: "/blog/integrar-google-ads-crm-whatsapp",
    type: "article",
    description: "Conecte landing page ao funil comercial completo — do clique ao fechamento.",
  }),
  h2("Erros que destroem conversão"),
  ul([
    "Headline genérica desconectada do anúncio",
    "Formulário com 8+ campos no primeiro contato",
    "Zero prova social ou depoimentos inventados",
    "Página lenta (> 4s no mobile)",
    "Menu completo com links para blog, sobre, carreiras",
    "CTA único no final da página — visitante nunca scrolla até lá",
    "Copy focado em empresa, não em benefício do visitante",
  ]),
  cta({
    title: "Audite sua landing page gratuitamente",
    description:
      "Diagnóstico Raise One identifica gaps de conversão, velocidade e alinhamento com campanhas pagas.",
    primaryLabel: "Fazer diagnóstico gratuito",
    primaryHref: "/diagnostico",
    secondaryLabel: "Ver elementos no case UNIP",
    secondaryHref: "/cases/unip",
  }),
  p("Landing page de captação é onde investimento em mídia se transforma em lead — ou se perde. Os 12 elementos deste checklist são anatomia de páginas que convertem consistentemente. Audite, implemente, teste e itere."),
  h2("Variações por segmento"),
  p("Os 12 elementos são universais; ênfase muda por mercado. Clínicas estéticas: hero visual e prova social (antes/depois) pesam mais. B2B: objeções e trust signals (cases, certificações) são críticos. Educação: urgência de vestibular e credenciais MEC. Imobiliário: hero do empreendimento, planta e localização. Adapte profundidade de cada elemento ao ciclo de decisão e ticket do segmento."),
  h2("Ferramentas para construir e otimizar"),
  ul([
    "Construção: Webflow, Framer, WordPress + Elementor, ou LP custom em React",
    "Heatmaps: Microsoft Clarity (gratuito), Hotjar",
    "A/B testing: Google Optimize alternativas, testes nativos em ferramentas de LP",
    "Velocidade: PageSpeed Insights, WebPageTest",
    "Formulários: integração nativa com CRM ou Typeform → webhook",
  ]),
  h2("Checklist de auditoria rápida (5 minutos)"),
  p("Abra sua landing page no mobile e responda:"),
  ol([
    "Headline comunica o que o anúncio prometeu?",
    "Consigo ver CTA ou formulário sem scrollar?",
    "Página carrega em menos de 3 segundos?",
    "Existe prova social visível na primeira tela?",
    "Formulário pede no máximo 4 campos?",
    "Há botão WhatsApp acessível?",
    "Política de privacidade está linkada?",
  ]),
  p("Três ou mais respostas 'não' indicam oportunidade imediata de melhoria — provavelmente maior impacto que otimizar campanhas no Google Ads."),
  h2("Copywriting para conversão"),
  p("Elementos visuais atraem; copy converte. Headline promete resultado. Subheadline explica como. Benefícios traduzem features em outcomes. Objeções antecipam 'é caro?', 'funciona para mim?', 'posso confiar?'. Use linguagem do cliente — não jargão interno. 'Harmonização facial personalizada' converte menos que 'Resultado natural sem exageros — avaliação gratuita'. Teste copy com pessoas reais do público-alvo antes de escalar tráfego."),
  h2("Próximos passos após implementar os 12 elementos"),
  p("Com checklist completo, priorize: (1) velocidade mobile, (2) teste A/B de headline, (3) integração formulário → CRM → WhatsApp, (4) heatmap para identificar abandono no formulário. Landing page otimizada sem follow-up comercial rápido ainda perde leads — LP é início do funil, não fim."),
  p("Revise landing page a cada nova campanha ou oferta — LP envelhecida com promoção expirada ou estoque esgotado destrói confiança e Quality Score. Trate landing page como produto vivo, não peça estática publicada uma vez."),
  p("Os 12 elementos funcionam em conjunto — remover prova social para 'limpar' design ou encurtar formulário além do necessário costuma reduzir conversão. Simplicidade visual sim; omissão estratégica não."),
];

const faq = [
  {
    question: "Quantos elementos posso omitir e ainda converter?",
    answer:
      "Mínimo viável: headline alinhada, CTA, formulário enxuto e mobile ok. Porém, prova social, objeções e trust signals frequentemente dobram taxa de conversão. Quanto maior ticket ou ciclo de decisão, mais elementos são críticos.",
  },
  {
    question: "Uma landing page serve para Google Ads e Meta Ads?",
    answer:
      "Pode, se copy do hero for neutro o suficiente. Idealmente, adapte headline e hero por canal — intenção de busca (Google) difere de interrupção visual (Meta). Mesma estrutura, copy ajustada.",
  },
  {
    question: "Qual taxa de conversão é boa para landing page?",
    answer:
      "Varia por setor: serviços locais 3–8%, B2B 2–5%, e-commerce 1–3%. Abaixo de 2% em serviços locais com tráfego qualificado indica problema estrutural — não apenas copy.",
  },
  {
    question: "Preciso de designer ou posso usar template?",
    answer:
      "Templates aceleram, mas genéricos convertem menos. Design alinhado à marca, com hero real e prova social específica supera template bonito sem substância. Investimento em LP dedicada se paga rapidamente em campanhas ativas.",
  },
  {
    question: "Com que frequência devo testar A/B?",
    answer:
      "Um teste por vez, com mínimo 100 conversões ou 2 semanas (o que vier depois). Priorize: headline, CTA, formulário. Testes simultâneos de múltiplos elementos confundem resultados.",
  },
];

export const landingPageCaptacaoLeadsElementos: BlogArticle = {
  slug,
  title: "Landing page para captação de leads: 12 elementos essenciais",
  excerpt:
    "Checklist completo dos 12 elementos que toda landing page de captação precisa — com detalhes de execução, estrutura recomendada e erros que destroem conversão em campanhas pagas.",
  category: "growth",
  type: "guia",
  readTime: estimateReadTime(sections, faq),
  publishedAt: "2026-07-25",
  modifiedAt: "2026-08-05",
  author: "Raise One",
  pillar: "presenca",
  featuredImage: blogFeatured(slug),
  seo: {
    title: "Landing page captação de leads: 12 elementos | Raise One",
    description:
      "Checklist dos 12 elementos essenciais de landing page para captação: headline, CTA, formulário, prova social, mobile e otimização contínua.",
  },
  targetKeywords: [
    "landing page captação leads",
    "elementos landing page conversão",
    "landing page google ads",
    "checklist landing page",
    "otimizar landing page leads",
  ],
  relatedSlugs: [
    "landing-page-vs-site-institucional",
    "como-estruturar-campanhas-google-ads",
    "integrar-google-ads-crm-whatsapp",
  ],
  relatedLinks: [
    { label: "Case UNIP", href: "/cases/unip", type: "case" },
    { label: "Diagnóstico", href: "/diagnostico", type: "solution" },
  ],
  sections,
  faq,
};
