import type { ExecutionState } from "./types";
import { seedPhase2Data } from "./seed-phase2";

export function createSeedState(): ExecutionState {
  const now = new Date().toISOString();
  const phase2 = seedPhase2Data();

  return {
    version: 3,
    planStartDate: "2026-06-16",
    currentWeek: 1,
    northStar: {
      priorityOne:
        "Definir escopo dos produtos + contratar editor freelancer + centralizar operação",
      hoursGoalMonthly: 50,
      clientSlotsGoal: 2,
      clientSlotsCurrent: 0,
    },
    bottlenecks: [
      {
        id: "bn-edicao",
        name: "Edição de vídeo",
        severity: "critical",
        impact: "Impede +2 clientes grandes",
        owner: "vini",
        targetDate: "2026-06-20",
        queueCount: 23,
        avgDelayDays: 8,
        status: "active",
        order: 1,
      },
      {
        id: "bn-escopo",
        name: "Escopo / favorzinhos",
        severity: "high",
        impact: "~8h/semana perdidas",
        owner: "vini",
        status: "monitoring",
        order: 2,
      },
      {
        id: "bn-notion",
        name: "Operação manual (Notion)",
        severity: "high",
        impact: "~12h/semana em gestão",
        owner: "luan",
        status: "monitoring",
        order: 3,
      },
      {
        id: "bn-whatsapp",
        name: "Interrupções WhatsApp",
        severity: "high",
        impact: "Dias inteiros de planejamento perdidos",
        owner: "caio",
        status: "monitoring",
        order: 4,
      },
    ],
    delegations: [
      {
        id: "del-edicao",
        activity: "Editar vídeo",
        todayOwner: "Vini",
        targetOwner: "freelancer",
        hoursPerWeek: 25,
        status: "in_transition",
        hoursRecovered: 18,
        transitionOwner: "vini",
        dueDate: "2026-06-20",
      },
      {
        id: "del-comentarios",
        activity: "Comentários Instagram",
        todayOwner: "Vini",
        targetOwner: "caio",
        hoursPerWeek: 5,
        status: "delegated",
        hoursRecovered: 6,
        transitionOwner: "vini",
      },
      {
        id: "del-briefing",
        activity: "Briefing edição",
        todayOwner: "Caio",
        targetOwner: "editor",
        hoursPerWeek: 8,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "caio",
      },
      {
        id: "del-trafego-mf",
        activity: "Tráfego AMF/MF",
        todayOwner: "Vini",
        targetOwner: "luan",
        hoursPerWeek: 6,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "vini",
        dueDate: "2026-07-01",
      },
      {
        id: "del-calendario",
        activity: "Preencher calendário / esteira",
        todayOwner: "Vini",
        targetOwner: "sistema",
        hoursPerWeek: 4,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "luan",
      },
      {
        id: "del-social",
        activity: "Gestão social media básica",
        todayOwner: "Vini",
        targetOwner: "caio",
        hoursPerWeek: 5,
        status: "in_transition",
        hoursRecovered: 0,
        transitionOwner: "vini",
      },
      {
        id: "del-notion",
        activity: "Manter Notion atualizado",
        todayOwner: "Vini",
        targetOwner: "sistema",
        hoursPerWeek: 12,
        status: "in_transition",
        hoursRecovered: 12,
        transitionOwner: "caio",
      },
      {
        id: "del-gravacao",
        activity: "Gravação de conteúdo",
        todayOwner: "Vini + Caio",
        targetOwner: "freelancer",
        hoursPerWeek: 15,
        status: "not_started",
        hoursRecovered: 0,
      },
      {
        id: "del-onboarding",
        activity: "Onboarding técnico (pixels/tags)",
        todayOwner: "Vini",
        targetOwner: "luan",
        hoursPerWeek: 8,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "luan",
      },
      {
        id: "del-catalogo",
        activity: "Definição catálogo / contratos",
        todayOwner: "Luan",
        targetOwner: "sistema",
        hoursPerWeek: 4,
        status: "in_transition",
        hoursRecovered: 0,
        transitionOwner: "luan",
      },
      {
        id: "del-jasa",
        activity: "Demandas avulsas corretores (Nobre)",
        todayOwner: "Vini + Caio",
        targetOwner: "freelancer",
        hoursPerWeek: 6,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "vini",
        dueDate: "2026-06-22",
      },
      {
        id: "del-publicacao",
        activity: "Agendamento de publicação",
        todayOwner: "Caio",
        targetOwner: "sistema",
        hoursPerWeek: 3,
        status: "not_started",
        hoursRecovered: 0,
        transitionOwner: "luan",
      },
    ],
    planDeliveries: [
      {
        id: "w1-1",
        week: 1,
        number: 1,
        title: "Catálogo de produtos v1 aprovado (Doc 03 preenchido)",
        owner: "luan",
        dueDate: "2026-06-18",
        doneWhen: "Vini e Caio validaram preços e pacotes",
        status: "pending",
        delegationId: "del-catalogo",
      },
      {
        id: "w1-2",
        week: 1,
        number: 2,
        title: "Editor freelancer contatado + 1 vídeo teste enviado",
        owner: "vini",
        dueDate: "2026-06-20",
        doneWhen: "Vídeo editado recebido e aprovado ou descartado",
        status: "pending",
        delegationId: "del-edicao",
      },
      {
        id: "w1-3",
        week: 1,
        number: 3,
        title: "Mapa da fila atual (Nobre + AMF + Contato)",
        owner: "caio",
        dueDate: "2026-06-19",
        doneWhen: "Planilha/Notion com cliente, vídeos pendentes, dias de atraso",
        status: "pending",
      },
      {
        id: "w1-4",
        week: 1,
        number: 4,
        title: "Reunião Jasa (Nobre) — escopo corretores",
        owner: "vini",
        dueDate: "2026-06-22",
        doneWhen: "Acordo: add-on, aumento ou corte definido",
        status: "pending",
        delegationId: "del-jasa",
      },
      {
        id: "w2-1",
        week: 2,
        number: 1,
        title: "Notion unificado (clientes, projetos, tarefas, produções)",
        owner: "luan",
        dueDate: "2026-06-26",
        doneWhen: "Os 3 usam o mesmo workspace",
        status: "pending",
        delegationId: "del-notion",
      },
      {
        id: "w2-2",
        week: 2,
        number: 2,
        title: "SOP: Onboarding 30 dias",
        owner: "luan",
        dueDate: "2026-06-27",
        doneWhen: "Checklist copiável no Notion",
        status: "pending",
      },
      {
        id: "w2-3",
        week: 2,
        number: 3,
        title: "SOP: Fluxo de edição completo",
        owner: "caio",
        dueDate: "2026-06-27",
        doneWhen: "1 vídeo passou pelo fluxo completo",
        status: "pending",
        delegationId: "del-briefing",
      },
      {
        id: "w2-4",
        week: 2,
        number: 4,
        title: "Template de contrato com cláusula de escopo",
        owner: "luan",
        dueDate: "2026-06-25",
        doneWhen: "Pronto para novos fechamentos",
        status: "pending",
      },
      {
        id: "w2-5",
        week: 2,
        number: 5,
        title: "Alinhar AMF sobre campanha 08/07 (escopo fechado)",
        owner: "vini",
        dueDate: "2026-06-24",
        doneWhen: "Cliente confirmou entregas e prazos",
        status: "pending",
      },
      {
        id: "w3-1",
        week: 3,
        number: 1,
        title: "Editor produzindo mín. 50% da fila",
        owner: "vini",
        dueDate: "2026-07-04",
        doneWhen: "Metade dos vídeos sem edição interna",
        status: "pending",
        delegationId: "del-edicao",
      },
      {
        id: "w3-2",
        week: 3,
        number: 2,
        title: "Alinhamento escopo com 3 clientes recorrentes",
        owner: "vini",
        dueDate: "2026-07-03",
        doneWhen: "Conversa feita + add-ons documentados",
        status: "pending",
      },
      {
        id: "w3-3",
        week: 3,
        number: 3,
        title: "Documento padrão de edição por cliente (Nobre, AMF)",
        owner: "caio",
        dueDate: "2026-07-02",
        doneWhen: "Freelancer edita sem perguntar estilo",
        status: "pending",
      },
      {
        id: "w3-4",
        week: 3,
        number: 4,
        title: "Passar 1 demanda de tráfego MF para Luan",
        owner: "vini",
        dueDate: "2026-07-01",
        doneWhen: "Luan operando conta com supervisão",
        status: "pending",
        delegationId: "del-trafego-mf",
      },
      {
        id: "w3-5",
        week: 3,
        number: 5,
        title: "Automatizar agendamento de publicação",
        owner: "luan",
        dueDate: "2026-07-05",
        doneWhen: "Pelo menos 1 cliente no auto-schedule",
        status: "pending",
        delegationId: "del-publicacao",
      },
      {
        id: "w4-1",
        week: 4,
        number: 1,
        title: "Retomar 1 das 2 propostas em aberto",
        owner: "vini",
        dueDate: "2026-07-10",
        doneWhen: "Proposta reenviada ou call marcada",
        status: "pending",
      },
      {
        id: "w4-2",
        week: 4,
        number: 2,
        title: "Review de métricas do mês",
        owner: "luan",
        dueDate: "2026-07-11",
        doneWhen: "Tabela preenchida com dados reais",
        status: "pending",
      },
      {
        id: "w4-3",
        week: 4,
        number: 3,
        title: "Avaliar editor: continuar, trocar ou +1",
        owner: "vini",
        dueDate: "2026-07-09",
        doneWhen: "Decisão documentada",
        status: "pending",
        delegationId: "del-edicao",
      },
      {
        id: "w4-4",
        week: 4,
        number: 4,
        title: "Campanha AMF 08/07 executada dentro do escopo",
        owner: "vini",
        dueDate: "2026-07-08",
        doneWhen: "Entregue sem estourar outros clientes",
        status: "pending",
      },
      {
        id: "w4-5",
        week: 4,
        number: 5,
        title: "Retro mensal do time",
        owner: "luan",
        dueDate: "2026-07-13",
        doneWhen: "45 min feitos, ajustes definidos",
        status: "pending",
      },
    ],
    backlog: [
      {
        id: "bl-1",
        title: "Definir catálogo de produtos v1",
        owner: "luan",
        column: "agora",
        source: "Reunião 15/06",
      },
      {
        id: "bl-2",
        title: "Contratar/validar editor freelancer",
        owner: "vini",
        column: "agora",
        source: "Reunião 15/06",
      },
      {
        id: "bl-3",
        title: "Mapear fila de edição atual",
        owner: "caio",
        column: "agora",
        source: "Reunião 15/06",
      },
      {
        id: "bl-4",
        title: "Notion unificado",
        owner: "luan",
        column: "proximo",
        dependency: "Catálogo definido",
      },
      {
        id: "bl-5",
        title: "SOP onboarding 30 dias",
        owner: "luan",
        column: "proximo",
        dependency: "Notion pronto",
      },
      {
        id: "bl-6",
        title: "SOP fluxo de edição",
        owner: "caio",
        column: "proximo",
        dependency: "Editor validado",
      },
      {
        id: "bl-7",
        title: "Template contrato com escopo",
        owner: "luan",
        column: "proximo",
        dependency: "Catálogo definido",
      },
      {
        id: "bl-8",
        title: "Alinhar clientes recorrentes (escopo)",
        owner: "vini",
        column: "proximo",
        dependency: "Template pronto",
      },
      {
        id: "bl-9",
        title: "Retomar 2 propostas em aberto",
        owner: "vini",
        column: "depois",
      },
      {
        id: "bl-10",
        title: "Fechar Sibeli (RE/MAX)",
        owner: "luan",
        column: "depois",
      },
      {
        id: "bl-11",
        title: "LP captura R1 + tráfego",
        owner: "luan",
        column: "depois",
      },
      {
        id: "bl-12",
        title: "SaaS / portal imobiliário",
        owner: "luan",
        column: "nao_agora",
      },
      {
        id: "bl-13",
        title: "Mercado de eventos / casamentos",
        owner: "vini",
        column: "nao_agora",
      },
      {
        id: "bl-14",
        title: "Agente por cliente (JARVIS)",
        owner: "luan",
        column: "nao_agora",
      },
    ],
    immediateActions: [
      {
        id: "ia-1",
        title: "Conversar com editora (Patrícia) e orçar edição por vídeo",
        owner: "vini",
        done: false,
      },
      {
        id: "ia-2",
        title: "Finalizar catálogo de produtos com escopo fechado",
        owner: "luan",
        done: false,
      },
      {
        id: "ia-3",
        title: "Mapear fila atual de edição por cliente (Nobre, AMF, Contato)",
        owner: "caio",
        done: false,
      },
      {
        id: "ia-4",
        title: "Alinhar com clientes recorrentes nova política de escopo",
        owner: "vini",
        done: false,
      },
      {
        id: "ia-5",
        title: "Migrar estrutura do Notion do Vini para template unificado",
        owner: "luan",
        done: false,
      },
    ],
    metrics: {
      productionQueue: 23,
      avgDelayDays: 8,
    },
    ...phase2,
    hoursHistory: [
      {
        id: "hs-seed-1",
        date: "2026-06-09",
        week: 0,
        weekLabel: "Baseline",
        hoursRecovered: 24,
        hoursGoal: 50,
        delegatedCount: 0,
        totalDelegations: 12,
        productionQueue: 28,
        avgDelayDays: 10,
        source: "manual",
      },
      {
        id: "hs-seed-2",
        date: "2026-06-14",
        week: 0,
        weekLabel: "Pré-planning",
        hoursRecovered: 30,
        hoursGoal: 50,
        delegatedCount: 1,
        totalDelegations: 12,
        productionQueue: 25,
        avgDelayDays: 9,
        source: "manual",
      },
    ],
    updatedAt: now,
  };
}
