import type { DiscoveryObjective } from "../../types";

/**
 * Diagnostic Knowledge Graph — Qualificação Comercial v1
 * Derivado do roteiro Angélica (Saúde & Cia) — matéria-prima, não checklist linear.
 */
export const QUALIFICATION_V1_OBJECTIVES: DiscoveryObjective[] = [
  // ── BUSINESS ──────────────────────────────────────────────
  {
    key: "business_history",
    domain: "business",
    label: "História do negócio",
    description: "Como a empresa começou e evoluiu.",
    whyItMatters: "Contexto de autoridade, maturidade e narrativa comercial.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Narrativa resumida da origem e trajetória.",
    questions: [
      "Conta um pouco da história da empresa. Como começou?",
      "Há quanto tempo vocês trabalham com isso?",
    ],
    relatedObjectives: ["market_entry_motivation", "differentiator"],
    confidenceThreshold: 0.6,
  },
  {
    key: "operation_structure",
    domain: "business",
    label: "Estrutura operacional",
    description: "Quem opera o negócio e como.",
    whyItMatters: "Capacidade de execução e decisão.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Quem toca operação, equipe, centralização.",
    questions: [
      "Hoje, como funciona a operação? É você que toca tudo ou tem mais pessoas?",
    ],
    relatedObjectives: ["service_capacity"],
    confidenceThreshold: 0.6,
  },
  {
    key: "market_entry_motivation",
    domain: "business",
    label: "Motivação de entrada no mercado",
    description: "Por que entraram nesse mercado.",
    whyItMatters: "Personal branding, narrativa e posicionamento emocional.",
    importance: "low",
    captureType: "text",
    requiredEvidence: "Motivação pessoal ou de mercado declarada.",
    questions: ["O que fez você entrar nesse mercado?"],
    positiveSignals: ["minha mãe", "família", "comecei porque", "história"],
    confidenceThreshold: 0.5,
  },
  {
    key: "differentiator",
    domain: "business",
    label: "Diferencial percebido",
    description: "O que diferencia da concorrência regional.",
    whyItMatters: "Posicionamento e proposta de valor.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Diferencial declarado pelo prospect.",
    questions: [
      "O que você sente que diferencia vocês de outras empresas da região?",
    ],
    relatedObjectives: ["brand_desired_perception"],
    confidenceThreshold: 0.6,
  },

  // ── OFFER ─────────────────────────────────────────────────
  {
    key: "product_portfolio",
    domain: "offer",
    label: "Portfólio de produtos",
    description: "Quais produtos/serviços a empresa oferece.",
    whyItMatters: "Base para escopo e priorização de projeto.",
    importance: "critical",
    captureType: "list",
    requiredEvidence: "Lista de produtos ou serviços oferecidos.",
    questions: ["Quais produtos vocês oferecem hoje?"],
    relatedObjectives: ["strategic_product_priority"],
    proposalCritical: true,
    confidenceThreshold: 0.7,
  },
  {
    key: "top_selling_product",
    domain: "offer",
    label: "Produto que mais vende",
    description: "Produto com maior volume de vendas.",
    whyItMatters: "Entender tração atual vs desejo estratégico.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Nome do produto mais vendido.",
    questions: [
      "Desses produtos, qual é o que mais vende atualmente?",
      "Qual deles representa a maior parte do faturamento?",
    ],
    dependencies: ["product_portfolio"],
    confidenceThreshold: 0.6,
  },
  {
    key: "most_profitable_product",
    domain: "offer",
    label: "Produto mais rentável",
    description: "Produto com melhor margem/comissão.",
    whyItMatters: "Economics e priorização comercial.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Produto mais lucrativo para a empresa.",
    questions: ["Existe algum produto que seja mais lucrativo para vocês?"],
    relatedObjectives: ["avg_commission"],
    confidenceThreshold: 0.6,
  },
  {
    key: "strategic_product_priority",
    domain: "offer",
    label: "Produto estratégico prioritário",
    description: "Produto que querem crescer nos próximos meses.",
    whyItMatters: "Define foco da proposta Raise One.",
    importance: "critical",
    captureType: "text",
    requiredEvidence: "Produto escolhido para priorizar.",
    questions: [
      "Tem algum produto que vocês gostariam de vender muito mais?",
      "Se tivesse que escolher apenas UM produto para trabalharmos, qual seria?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.7,
  },
  {
    key: "excluded_product",
    domain: "offer",
    label: "Produto excluído de prioridade",
    description: "Produto que não querem crescer.",
    whyItMatters: "Evita proposta desalinhada.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Produto explicitamente descartado.",
    questions: ["Tem algum produto que vocês não têm interesse em crescer?"],
    confidenceThreshold: 0.6,
  },

  // ── CUSTOMER / ICP ────────────────────────────────────────
  {
    key: "current_icp",
    domain: "customer",
    label: "Cliente que mais compra hoje",
    description: "Perfil do cliente atual dominante.",
    whyItMatters: "ICP real vs ICP desejado.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Descrição do cliente que mais compra.",
    questions: ["Quem é o cliente que mais compra de vocês hoje?"],
    relatedObjectives: ["desired_icp"],
    confidenceThreshold: 0.6,
  },
  {
    key: "desired_icp",
    domain: "customer",
    label: "Cliente desejado",
    description: "Perfil de cliente que querem atrair mais.",
    whyItMatters: "Targeting de aquisição e conteúdo.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Perfil desejado declarado.",
    questions: ["E quem é o cliente que vocês gostariam de ter mais?"],
    confidenceThreshold: 0.6,
  },
  {
    key: "customer_type",
    domain: "customer",
    label: "Tipo de cliente",
    description: "Pessoa física vs empresa.",
    whyItMatters: "Canal, mensagem e produto.",
    importance: "high",
    captureType: "enum",
    requiredEvidence: "PF, PJ ou mix.",
    questions: ["Vocês trabalham mais com pessoa física ou empresa?"],
    proposalCritical: true,
    confidenceThreshold: 0.7,
  },
  {
    key: "customer_geography",
    domain: "customer",
    label: "Geografia dos clientes",
    description: "Cidades/regiões de origem dos clientes.",
    whyItMatters: "Geo-targeting e SEO local.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Cidades ou região principal.",
    questions: ["De quais cidades vêm seus clientes?"],
    confidenceThreshold: 0.6,
  },
  {
    key: "primary_pain",
    domain: "customer",
    label: "Dor principal do cliente",
    description: "O que leva o cliente a procurá-los.",
    whyItMatters: "Messaging e landing pages.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Dor principal declarada.",
    questions: [
      "Qual é a principal dor que faz essa pessoa procurar vocês?",
    ],
    confidenceThreshold: 0.6,
  },
  {
    key: "main_objections",
    domain: "customer",
    label: "Principais objeções",
    description: "O que faz o prospect desistir.",
    whyItMatters: "Copy, follow-up e qualificação.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Objeções recorrentes.",
    questions: [
      "Quais são as principais objeções? O que faz a pessoa desistir?",
    ],
    confidenceThreshold: 0.6,
  },

  // ── COMMERCIAL ────────────────────────────────────────────
  {
    key: "sales_process_overview",
    domain: "commercial",
    label: "Processo comercial",
    description: "Fluxo do primeiro contato até virar cliente.",
    whyItMatters: "Gargalos de conversão e automação.",
    importance: "critical",
    captureType: "text",
    requiredEvidence: "Descrição do funil comercial.",
    questions: [
      "Quando alguém entra em contato hoje, como funciona o atendimento até virar cliente?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.6,
  },
  {
    key: "contact_channels",
    domain: "commercial",
    label: "Canais de contato",
    description: "Por onde chegam os contatos.",
    whyItMatters: "Integração com aquisição e tracking.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Canais principais de entrada.",
    questions: ["Por onde normalmente esse contato chega?"],
    relatedObjectives: ["primary_acquisition_channel"],
    confidenceThreshold: 0.6,
  },
  {
    key: "response_time",
    domain: "commercial",
    label: "Tempo de resposta",
    description: "Quanto tempo levam para responder leads.",
    whyItMatters: "Conversão e SLA comercial.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Tempo médio de resposta.",
    questions: ["Quanto tempo normalmente vocês levam para responder?"],
    confidenceThreshold: 0.6,
  },
  {
    key: "follow_up_process",
    domain: "commercial",
    label: "Processo de follow-up",
    description: "Como fazem follow-up quando não fecham na hora.",
    whyItMatters: "Maturidade comercial e CRM.",
    importance: "high",
    captureType: "enum",
    requiredEvidence: "Processo definido, informal ou inexistente.",
    questions: [
      "Vocês costumam fazer follow-up quando a pessoa não fecha na hora?",
      "Existe algum processo definido ou depende de cada atendimento?",
    ],
    positiveSignals: ["não", "informal", "quando lembramos", "depende"],
    confidenceThreshold: 0.6,
  },
  {
    key: "lead_volume",
    domain: "commercial",
    label: "Volume de leads",
    description: "Volume mensal aproximado de novos contatos.",
    whyItMatters: "Capacidade, CAC, funil e meta.",
    importance: "critical",
    captureType: "numeric_range",
    requiredEvidence: "Estimativa numérica mensal de contatos.",
    questions: [
      "Quantos contatos novos vocês recebem aproximadamente por mês?",
      "Você tem uma ideia de quantas pessoas novas entram em contato?",
    ],
    dependencies: ["contact_channels"],
    relatedObjectives: ["sales_volume", "conversion_rate", "service_capacity"],
    proposalCritical: true,
    confidenceThreshold: 0.65,
  },
  {
    key: "proposal_volume",
    domain: "commercial",
    label: "Volume de propostas",
    description: "Quantas propostas/cotações por mês.",
    whyItMatters: "Taxa de avanço no funil.",
    importance: "high",
    captureType: "numeric_range",
    requiredEvidence: "Estimativa mensal de propostas.",
    questions: [
      "Desses contatos, aproximadamente quantos viram proposta?",
    ],
    dependencies: ["lead_volume"],
    confidenceThreshold: 0.65,
  },
  {
    key: "sales_volume",
    domain: "commercial",
    label: "Volume de vendas",
    description: "Quantos clientes fecham por mês.",
    whyItMatters: "Conversão e meta de crescimento.",
    importance: "critical",
    captureType: "numeric_range",
    requiredEvidence: "Estimativa mensal de vendas.",
    questions: ["E quantos acabam virando clientes?"],
    relatedObjectives: ["conversion_rate", "numeric_growth_target"],
    proposalCritical: true,
    confidenceThreshold: 0.65,
  },
  {
    key: "conversion_rate",
    domain: "commercial",
    label: "Taxa de conversão",
    description: "Taxa aproximada lead → venda.",
    whyItMatters: "Diagnóstico de gargalo comercial.",
    importance: "high",
    captureType: "numeric",
    requiredEvidence: "Percentual ou ratio inferido ou declarado.",
    questions: ["Vocês têm ideia da taxa de fechamento?"],
    dependencies: ["lead_volume", "sales_volume"],
    confidenceThreshold: 0.5,
  },
  {
    key: "service_capacity",
    domain: "commercial",
    label: "Capacidade de atendimento",
    description: "Capacidade de absorver mais demanda.",
    whyItMatters: "Limita investimento em aquisição.",
    importance: "high",
    captureType: "enum",
    requiredEvidence: "Alta, média ou limitada.",
    questions: [
      "Hoje vocês conseguiriam atender tranquilamente o dobro de contatos?",
    ],
    confidenceThreshold: 0.6,
  },

  // ── ECONOMICS ─────────────────────────────────────────────
  {
    key: "avg_sale_value",
    domain: "economics",
    label: "Valor médio de venda",
    description: "Ticket médio aproximado.",
    whyItMatters: "ROI de mídia e proposta.",
    importance: "high",
    captureType: "numeric_range",
    requiredEvidence: "Valor estimado por venda.",
    questions: ["Qual é aproximadamente o valor médio de uma venda?"],
    proposalCritical: true,
    confidenceThreshold: 0.6,
  },
  {
    key: "avg_commission",
    domain: "economics",
    label: "Comissão média",
    description: "Quanto ganham por venda em média.",
    whyItMatters: "Economics e budget de aquisição.",
    importance: "critical",
    captureType: "numeric_range",
    requiredEvidence: "Comissão ou margem estimada.",
    questions: [
      "Em média, quanto vocês ganham ou comissionam em uma venda?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.6,
  },
  {
    key: "customer_ltv",
    domain: "economics",
    label: "LTV do cliente",
    description: "Valor do cliente ao longo do tempo.",
    whyItMatters: "Justifica investimento em aquisição.",
    importance: "high",
    captureType: "numeric_range",
    requiredEvidence: "Estimativa de valor lifetime.",
    questions: [
      "Quanto vale, aproximadamente, um bom cliente para vocês ao longo do tempo?",
    ],
    confidenceThreshold: 0.5,
  },
  {
    key: "recurrence_model",
    domain: "economics",
    label: "Recorrência / renovação",
    description: "Se há recompra ou comissão recorrente.",
    whyItMatters: "Modelo de receita e LTV.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Tipo de recorrência por produto.",
    questions: [
      "Um cliente costuma gerar novas vendas depois?",
      "Vocês fazem renovação? Existe recorrência em algum produto?",
    ],
    confidenceThreshold: 0.5,
  },

  // ── ACQUISITION ───────────────────────────────────────────
  {
    key: "primary_acquisition_channel",
    domain: "acquisition",
    label: "Principal fonte de clientes",
    description: "Canal dominante de aquisição.",
    whyItMatters: "Dependências e oportunidade de diversificação.",
    importance: "critical",
    captureType: "text",
    requiredEvidence: "Canal principal declarado.",
    questions: ["Hoje, qual é a principal fonte de novos clientes?"],
    relatedObjectives: ["referral_dependency"],
    proposalCritical: true,
    positiveSignals: ["indicação", "instagram", "google", "whatsapp"],
    confidenceThreshold: 0.7,
  },
  {
    key: "referral_dependency",
    domain: "acquisition",
    label: "Dependência de indicação",
    description: "Quanto o negócio depende de indicações.",
    whyItMatters: "Problema estratégico comum — destrava sequência comercial.",
    importance: "critical",
    captureType: "enum",
    requiredEvidence: "Grau de dependência de indicação.",
    questions: [
      "Quanto depende de indicação?",
      "A maioria dos clientes vem por indicação?",
    ],
    dependencies: ["primary_acquisition_channel"],
    relatedObjectives: ["lead_volume", "numeric_growth_target"],
    positiveSignals: ["indicação", "indicacao", "referral", "maioria"],
    confidenceThreshold: 0.65,
  },
  {
    key: "channel_mix",
    domain: "acquisition",
    label: "Mix de canais",
    description: "Instagram, Google, WhatsApp, parceiros.",
    whyItMatters: "Mapa de aquisição atual.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Canais ativos e contribuição relativa.",
    questions: [
      "Instagram gera clientes? Google gera? WhatsApp? Parceiros?",
    ],
    relatedObjectives: ["lead_volume", "referral_dependency"],
    confidenceThreshold: 0.6,
  },
  {
    key: "failed_acquisition_attempts",
    domain: "acquisition",
    label: "Tentativas que não funcionaram",
    description: "Histórico de canais/táticas fracassadas.",
    whyItMatters: "Evitar repetir erro; entender frustração.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "O que tentaram e não funcionou.",
    questions: [
      "Existe alguma coisa que vocês já tentaram e não funcionou?",
    ],
    confidenceThreshold: 0.5,
  },

  // ── MARKETING ─────────────────────────────────────────────
  {
    key: "ads_investment_history",
    domain: "marketing",
    label: "Histórico de anúncios",
    description: "Se já investiram em mídia paga.",
    whyItMatters: "Maturidade e expectativas.",
    importance: "high",
    captureType: "boolean",
    requiredEvidence: "Sim/não + contexto.",
    questions: ["Vocês já investiram em anúncios alguma vez?"],
    relatedObjectives: ["google_ads_history", "meta_ads_history"],
    confidenceThreshold: 0.6,
  },
  {
    key: "google_ads_history",
    domain: "marketing",
    label: "Histórico Google Ads",
    description: "Experiência prévia com Google Ads.",
    whyItMatters: "Oportunidade Search + landing.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Nunca fez / fez e parou / faz atualmente.",
    questions: ["Google Ads?"],
    negativeSignals: ["nunca", "não fizemos", "nao fizemos"],
    confidenceThreshold: 0.6,
  },
  {
    key: "agency_history",
    domain: "marketing",
    label: "Histórico com agências",
    description: "Experiências anteriores com marketing terceirizado.",
    whyItMatters: "Confiança, expectativa e objeções.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Resumo de experiências passadas.",
    questions: [
      "Já contrataram agência ou profissional para marketing?",
    ],
    confidenceThreshold: 0.5,
  },
  {
    key: "digital_presence_perception",
    domain: "marketing",
    label: "Percepção da presença digital",
    description: "Como enxergam Google, Instagram e vitrine digital.",
    whyItMatters: "Gap entre percepção e realidade.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Percepção declarada sobre canais digitais.",
    questions: [
      "O que você gostaria que alguém encontrasse ao pesquisar vocês no Google?",
      "Como você enxerga o Instagram atualmente?",
    ],
    confidenceThreshold: 0.5,
  },

  // ── BRAND ─────────────────────────────────────────────────
  {
    key: "brand_desired_perception",
    domain: "brand",
    label: "Percepção desejada da marca",
    description: "O que querem que pensem ao ouvir o nome.",
    whyItMatters: "BrandCore e posicionamento.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Associação desejada da marca.",
    questions: [
      "Quando você fala o nome da empresa, o que gostaria que uma pessoa pensasse?",
    ],
    confidenceThreshold: 0.6,
  },
  {
    key: "personal_vs_institutional",
    domain: "brand",
    label: "Marca pessoal vs institucional",
    description: "Comunicação com rosto da fundadora vs empresa.",
    whyItMatters: "Estratégia de conteúdo e autoridade.",
    importance: "medium",
    captureType: "enum",
    requiredEvidence: "Preferência pessoal vs institucional.",
    questions: [
      "As pessoas procuram a empresa ou procuram você pessoalmente?",
      "Prefere comunicação institucional ou pessoal, como especialista?",
    ],
    positiveSignals: ["aparecer", "referência", "especialista", "pessoal"],
    confidenceThreshold: 0.5,
  },

  // ── CONTENT ───────────────────────────────────────────────
  {
    key: "content_willingness",
    domain: "content",
    label: "Disposição para conteúdo",
    description: "Gosto e disponibilidade para produzir conteúdo.",
    whyItMatters: "Viabilidade operacional do pacote.",
    importance: "medium",
    captureType: "enum",
    requiredEvidence: "Disposição e limitações.",
    questions: [
      "Você gosta de produzir conteúdo?",
      "Teria disponibilidade para gravações?",
    ],
    confidenceThreshold: 0.5,
  },
  {
    key: "content_format_preference",
    domain: "content",
    label: "Formato de conteúdo preferido",
    description: "Espontâneo vs produzido.",
    whyItMatters: "Escopo de produção.",
    importance: "low",
    captureType: "enum",
    requiredEvidence: "Preferência de formato.",
    questions: [
      "Prefere vídeos espontâneos ou algo mais produzido?",
    ],
    confidenceThreshold: 0.5,
  },

  // ── GOALS ─────────────────────────────────────────────────
  {
    key: "help_seeking_reason",
    domain: "goals",
    label: "Motivo de buscar ajuda agora",
    description: "Por que procuram marketing agora.",
    whyItMatters: "Urgência e fit comercial.",
    importance: "critical",
    captureType: "text",
    requiredEvidence: "Motivação e timing.",
    questions: [
      "Por que você está procurando ajuda com marketing agora?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.6,
  },
  {
    key: "primary_desired_result",
    domain: "goals",
    label: "Resultado principal desejado",
    description: "O que o marketing deve resolver.",
    whyItMatters: "North star da proposta.",
    importance: "critical",
    captureType: "text",
    requiredEvidence: "Resultado principal declarado.",
    questions: [
      "O que você gostaria que o marketing resolvesse?",
      "Reconhecimento, contatos ou vendas?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.6,
  },
  {
    key: "numeric_growth_target",
    domain: "goals",
    label: "Meta numérica de crescimento",
    description: "Número de clientes/leads desejado por mês.",
    whyItMatters: "Meta mensurável para proposta e mídia.",
    importance: "critical",
    captureType: "numeric_range",
    requiredEvidence: "Meta numérica aproximada.",
    questions: [
      "Quantos novos clientes por mês fariam diferença relevante?",
      "Existe algum número que gostaria de atingir por mês?",
    ],
    relatedObjectives: ["lead_volume", "sales_volume"],
    proposalCritical: true,
    confidenceThreshold: 0.65,
  },
  {
    key: "six_month_success_vision",
    domain: "goals",
    label: "Visão de sucesso em 6 meses",
    description: "O que teria acontecido se desse certo.",
    whyItMatters: "Alinhamento de expectativa e escopo.",
    importance: "high",
    captureType: "text",
    requiredEvidence: "Descrição do sucesso em 6 meses.",
    questions: [
      "Se o projeto desse certo nos próximos seis meses, o que teria acontecido?",
    ],
    confidenceThreshold: 0.6,
  },

  // ── EXPECTATIONS ──────────────────────────────────────────
  {
    key: "partner_expectation",
    domain: "expectations",
    label: "Expectativa sobre parceiro",
    description: "Executor vs parceiro estratégico.",
    whyItMatters: "Posicionamento Raise One.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Tipo de parceria esperada.",
    questions: [
      "Você espera alguém que execute ou que participe da estratégia?",
    ],
    confidenceThreshold: 0.5,
  },
  {
    key: "results_tracking_expectation",
    domain: "expectations",
    label: "Expectativa de acompanhamento",
    description: "Como querem ver leads, investimento e vendas.",
    whyItMatters: "Reporting e portal.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Métricas que querem acompanhar.",
    questions: [
      "Gostaria de saber quantos leads vieram, quanto foi investido e quantas vendas?",
    ],
    confidenceThreshold: 0.5,
  },

  // ── INVESTMENT ────────────────────────────────────────────
  {
    key: "monthly_marketing_budget",
    domain: "investment",
    label: "Orçamento mensal de marketing",
    description: "Verba destinada ao marketing mensalmente.",
    whyItMatters: "Proposal readiness — blocker comum.",
    importance: "critical",
    captureType: "numeric_range",
    requiredEvidence: "Faixa ou valor de budget mensal.",
    questions: [
      "Você já tem algum orçamento que pretende destinar ao marketing mensalmente?",
      "Tinha alguma faixa de investimento em mente?",
    ],
    proposalCritical: true,
    confidenceThreshold: 0.5,
  },
  {
    key: "project_vs_recurring_intent",
    domain: "investment",
    label: "Projeto pontual vs operação contínua",
    description: "Intenção de contratação.",
    whyItMatters: "Modelo comercial da proposta.",
    importance: "high",
    captureType: "enum",
    requiredEvidence: "Pontual ou recorrente.",
    questions: [
      "Está pensando em projeto pontual ou operação contínua?",
    ],
    confidenceThreshold: 0.5,
  },
  {
    key: "investment_mindset",
    domain: "investment",
    label: "Mentalidade sobre investimento",
    description: "Marketing como despesa vs ferramenta de crescimento.",
    whyItMatters: "Qualificação e upsell.",
    importance: "medium",
    captureType: "text",
    requiredEvidence: "Despesa vs investimento.",
    questions: [
      "Hoje o marketing é visto como despesa ou ferramenta de crescimento?",
    ],
    confidenceThreshold: 0.5,
  },
];

/** 10 perguntas críticas — gate mínimo para proposta inteligente */
export const CRITICAL_GATE_OBJECTIVES = [
  "sales_process_overview",
  "product_portfolio",
  "strategic_product_priority",
  "current_icp",
  "primary_acquisition_channel",
  "lead_volume",
  "help_seeking_reason",
  "six_month_success_vision",
  "monthly_marketing_budget",
  "numeric_growth_target",
] as const;
