import {
  Stethoscope,
  Smile,
  Scale,
  Building2,
  Calculator,
  Sun,
  Hammer,
  Wrench,
  HelpCircle,
  Car,
  GraduationCap,
  UtensilsCrossed,
  Landmark,
  PawPrint,
  Brain,
  CalendarCheck,
  Globe,
  MessageSquare,
  MousePointerClick,
  ScanSearch,
  Search,
  UserCheck,
  UserRound,
  SmilePlus,
  MapPin,
  Home,
} from "lucide-react";
import { createSegmentConfig } from "./base";

const sharedCompetitors = [
  {
    name: "Concorrente A — Especialistas Locais",
    isAd: true,
    url: "https://www.concorrentea.com.br",
    snippet: "Atendimento especializado na sua região. Agende sua avaliação e conheça nossos serviços.",
  },
  {
    name: "Concorrente B — Centro de Atendimento",
    isAd: true,
    url: "https://www.concorrenteb.com.br",
    snippet: "Profissionais qualificados com horários flexíveis. Avaliação gratuita disponível.",
  },
  {
    name: "Concorrente C — Clínica Premium",
    isAd: false,
    url: "https://www.concorrentec.com.br",
    snippet: "Referência em atendimento na região. Veja avaliações, serviços e formas de contato.",
  },
];

export const clinicaSegment = createSegmentConfig({
  slug: "clinica",
  name: "Clínica",
  hubLabel: "Clínica / Saúde",
  icon: Stethoscope,
  accentColor: "oklch(0.62 0.14 200)",
  accentSoft: "oklch(0.62 0.14 200 / 0.12)",
  seo: {
    title: "Raise One — Sua clínica deveria estar recebendo mais pacientes",
    description:
      "Diagnóstico gratuito para clínicas e consultórios. Descubra quantos pacientes em potencial estão indo para a concorrência na sua região.",
  },
  hero: {
    title: "Sua clínica deveria estar",
    titleHighlight: "capturando mais pacientes.",
    subtitle:
      "Todos os dias, pessoas da sua região pesquisam no Google por terapia, atendimento psicológico e acompanhamento em saúde mental. Se você não aparece, essa demanda está indo para quem aparece.",
    ctaLabel: "Quero minha análise de mercado",
    badge: "Especialistas em identificar oportunidades de aquisição para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.800",
  },
  visibility: {
    searchExamples: [
      "Psicólogo perto de mim",
      "Terapia online",
      "Atendimento psicológico",
      "Saúde mental",
      "Acompanhamento psicológico",
    ],
    ctaQuestion: "Quando pesquisam, sua clínica aparece?",
    businessType: "consultório",
    eyebrow: "01 — O Problema",
    title: "A maioria dos profissionais não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "atendimento acolhedor",
      "profissionais qualificados",
      "ambiente seguro",
      "pacientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu consultório.",
  },
  invisibleClient: { searchQuery: "psicólogo perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como novos pacientes",
    titleHighlight: "encontram profissionais no Google",
    steps: [
      { label: "Pessoa busca ajuda psicológica", icon: Brain },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Google mostra resultados", icon: Globe },
      { label: "Escolhe um profissional", icon: UserRound },
      { label: "Visita site ou perfil", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda consulta", icon: CalendarCheck },
      { label: "Torna-se paciente", icon: UserCheck },
    ],
    instagramNote: "A maioria dos profissionais tenta competir apenas no Instagram.",
    googleNote: "Mas a maioria dos pacientes inicia sua jornada de busca no Google.",
  },
  ahaMoment: {
    eyebrow: "04 — O Insight",
    title: "A maioria acredita que precisa de",
    titleHighlight: "mais divulgação.",
    subtitle:
      "Mas muitas vezes o problema é apenas não aparecer no momento certo — quando a pessoa já busca acolhimento e quer agendar.",
    winFlow: ["Pessoa pronta para terapia", "Pesquisa no Google", "Encontra você"],
    loseFlow: ["Pessoa pronta para terapia", "Pesquisa no Google", "Encontra concorrente"],
    winOutcome: "Você captura a oportunidade",
    loseOutcome: "A oportunidade vai embora",
  },
  demand: {
    bars: [
      { label: "Terapia", value: 88 },
      { label: "Saúde mental", value: 72 },
      { label: "Psicólogo online", value: 58 },
      { label: "Acompanhamento", value: 45 },
    ],
    totalSearches: "+1.920",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "05 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Centenas de pesquisas mensais por terapia e atendimento psicológico na sua região.",
      "Boa parte dessas pessoas nunca encontra seu consultório.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "clínica médica",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua clínica",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, clínicas da sua região estão aparecendo quando pacientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Consultório ou Especialidade",
    eyebrow: "Análise Gratuita",
    title: "Descubra quantas pessoas estão buscando",
    titleHighlight: "terapia na sua região.",
    subtitle:
      "Receba uma análise personalizada da demanda local — e entenda se você está aparecendo no momento certo.",
    submitLabel: "Quero minha análise de mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
  },
});

export const dentistaSegment = createSegmentConfig({
  slug: "dentista",
  name: "Dentista",
  hubLabel: "Dentista",
  icon: Smile,
  accentColor: "oklch(0.62 0.15 240)",
  accentSoft: "oklch(0.62 0.15 240 / 0.12)",
  seo: {
    title: "Raise One — Seu consultório deveria estar recebendo mais pacientes",
    description:
      "Diagnóstico gratuito para dentistas e clínicas odontológicas. Descubra quantos pacientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Seu consultório deveria estar",
    titleHighlight: "capturando mais pacientes.",
    subtitle:
      "Todos os dias, pessoas da sua região pesquisam no Google por implantes, clareamento, ortodontia e limpeza dental. Se você não aparece, essa demanda está indo para outro consultório.",
    ctaLabel: "Quero minha análise de mercado",
    badge: "Especialistas em identificar oportunidades de aquisição para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.600",
  },
  visibility: {
    searchExamples: [
      "Implante dentário",
      "Clareamento dental",
      "Ortodontia",
      "Dentista perto de mim",
      "Limpeza dental",
    ],
    ctaQuestion: "Quando pesquisam, seu consultório aparece?",
    businessType: "consultório",
    eyebrow: "01 — O Problema",
    title: "A maioria dos consultórios não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "atendimento humanizado",
      "profissionais qualificados",
      "equipamentos modernos",
      "pacientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu consultório.",
  },
  invisibleClient: { searchQuery: "implante dentário" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como novos pacientes",
    titleHighlight: "encontram dentistas no Google",
    steps: [
      { label: "Pessoa precisa de tratamento", icon: SmilePlus },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Google mostra consultórios", icon: Globe },
      { label: "Compara opções e avaliações", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda consulta", icon: CalendarCheck },
      { label: "Torna-se paciente", icon: UserCheck },
    ],
    instagramNote: "A maioria dos consultórios tenta competir apenas no Instagram.",
    googleNote: "Mas a maioria dos pacientes inicia sua busca no Google.",
  },
  ahaMoment: {
    eyebrow: "04 — O Insight",
    title: "A maioria acredita que precisa de",
    titleHighlight: "mais divulgação.",
    subtitle:
      "Mas muitas vezes o problema é apenas não aparecer no momento certo — quando a pessoa já decidiu tratar o sorriso.",
    winFlow: ["Paciente pronto para tratar", "Pesquisa no Google", "Encontra seu consultório"],
    loseFlow: ["Paciente pronto para tratar", "Pesquisa no Google", "Encontra concorrente"],
    winOutcome: "Você captura a oportunidade",
    loseOutcome: "A oportunidade vai embora",
  },
  demand: {
    bars: [
      { label: "Implantes", value: 85 },
      { label: "Clareamento", value: 70 },
      { label: "Ortodontia", value: 62 },
      { label: "Limpeza", value: 48 },
    ],
    totalSearches: "+1.540",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "05 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Centenas de pesquisas mensais por tratamentos odontológicos na sua região.",
      "Boa parte desses pacientes nunca encontra seu consultório.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "dentista",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu consultório",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, consultórios da sua região estão aparecendo quando pacientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Consultório ou Especialidade",
    eyebrow: "Análise Gratuita",
    title: "Descubra quantas pessoas estão buscando",
    titleHighlight: "tratamentos odontológicos na sua região.",
    subtitle:
      "Receba uma análise personalizada da demanda local — e entenda se seu consultório está aparecendo no momento certo.",
    submitLabel: "Quero minha análise de mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
  },
});

export const advogadoSegment = createSegmentConfig({
  slug: "advogado",
  name: "Advocacia",
  hubLabel: "Advocacia",
  icon: Scale,
  accentColor: "oklch(0.72 0.12 85)",
  accentSoft: "oklch(0.72 0.12 85 / 0.12)",
  seo: {
    title: "Raise One — Seu escritório deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para advogados e escritórios jurídicos. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Seu escritório deveria estar",
    titleHighlight: "capturando mais clientes.",
    subtitle:
      "Todos os dias, pessoas da sua região pesquisam no Google por advogados especializados em trabalhista, família, criminal e cível. Se você não aparece, essa demanda vai para a concorrência.",
    ctaLabel: "Quero minha análise de mercado",
    badge: "Especialistas em identificar oportunidades de aquisição para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+980",
  },
  visibility: {
    searchExamples: [
      "Advogado trabalhista",
      "Advogado criminalista",
      "Divórcio consensual",
      "Inventário",
      "Advogado perto de mim",
    ],
    ctaQuestion: "Quando pesquisam, seu escritório aparece?",
    businessType: "escritório",
    eyebrow: "01 — O Problema",
    title: "A maioria dos escritórios não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "atendimento confiável",
      "advogados experientes",
      "resultados comprovados",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu escritório.",
  },
  invisibleClient: { searchQuery: "advogado trabalhista" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como novos clientes",
    titleHighlight: "encontram advogados no Google",
    steps: [
      { label: "Pessoa precisa de orientação jurídica", icon: Scale },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Google mostra escritórios", icon: Globe },
      { label: "Avalia autoridade e especialidade", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda consulta", icon: CalendarCheck },
      { label: "Torna-se cliente", icon: UserCheck },
    ],
    instagramNote: "A maioria dos escritórios tenta competir apenas no Instagram.",
    googleNote: "Mas a maioria dos clientes inicia sua busca no Google.",
  },
  ahaMoment: {
    eyebrow: "04 — O Insight",
    title: "A maioria acredita que precisa de",
    titleHighlight: "mais divulgação.",
    subtitle:
      "Mas muitas vezes o problema é apenas não aparecer no momento certo — quando a pessoa já decidiu contratar um advogado.",
    winFlow: ["Cliente pronto para contratar", "Pesquisa no Google", "Encontra seu escritório"],
    loseFlow: ["Cliente pronto para contratar", "Pesquisa no Google", "Encontra concorrente"],
    winOutcome: "Você captura a oportunidade",
    loseOutcome: "A oportunidade vai embora",
  },
  demand: {
    bars: [
      { label: "Trabalhista", value: 82 },
      { label: "Família", value: 68 },
      { label: "Criminal", value: 55 },
      { label: "Cível", value: 42 },
    ],
    totalSearches: "+980",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "05 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Pessoas buscam advogados todos os dias na sua região.",
      "Muitos nunca encontram seu escritório.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "advogado",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu escritório",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, escritórios da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Escritório ou Área de Atuação",
    eyebrow: "Análise Gratuita",
    title: "Descubra quantas pessoas estão buscando",
    titleHighlight: "advogados na sua região.",
    subtitle:
      "Receba uma análise personalizada da demanda local — e entenda se seu escritório está aparecendo no momento certo.",
    submitLabel: "Quero minha análise de mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
  },
});

export const imobiliariaSegment = createSegmentConfig({
  slug: "imobiliaria",
  name: "Imobiliária",
  hubLabel: "Imobiliária",
  icon: Building2,
  accentColor: "oklch(0.65 0.14 145)",
  accentSoft: "oklch(0.65 0.14 145 / 0.12)",
  seo: {
    title: "Raise One — Sua imobiliária deveria estar recebendo mais leads",
    description:
      "Diagnóstico gratuito para imobiliárias. Descubra quantos compradores e locatários em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Sua imobiliária deveria estar",
    titleHighlight: "capturando mais oportunidades.",
    subtitle:
      "Todos os dias, pessoas da sua região pesquisam no Google por imóveis, aluguel, lançamentos e corretores. Se você não aparece, esses leads vão para outra imobiliária.",
    ctaLabel: "Quero minha análise de mercado",
    badge: "Especialistas em identificar oportunidades de aquisição para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+2.100",
  },
  visibility: {
    searchExamples: [
      "Apartamento à venda",
      "Aluguel de casas",
      "Imobiliária perto de mim",
      "Corretor de imóveis",
      "Lançamentos",
    ],
    ctaQuestion: "Quando pesquisam, sua imobiliária aparece?",
    businessType: "imobiliária",
    eyebrow: "01 — O Problema",
    title: "A maioria das imobiliárias não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "portfólio amplo",
      "corretores experientes",
      "atendimento personalizado",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua imobiliária.",
  },
  invisibleClient: { searchQuery: "apartamento à venda" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como compradores",
    titleHighlight: "encontram imóveis no Google",
    steps: [
      { label: "Pessoa busca imóvel ou corretor", icon: Home },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Google mostra opções locais", icon: MapPin },
      { label: "Explora imóveis e localização", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda visita", icon: CalendarCheck },
      { label: "Fecha negócio", icon: UserCheck },
    ],
    instagramNote: "A maioria das imobiliárias tenta competir apenas no Instagram.",
    googleNote: "Mas a maioria dos compradores inicia sua busca no Google.",
  },
  ahaMoment: {
    eyebrow: "04 — O Insight",
    title: "A maioria acredita que precisa de",
    titleHighlight: "mais divulgação.",
    subtitle:
      "Mas muitas vezes o problema é apenas não aparecer no momento certo — quando a pessoa já está pronta para comprar ou alugar.",
    winFlow: ["Comprador pronto para fechar", "Pesquisa imóvel", "Encontra sua imobiliária"],
    loseFlow: ["Comprador pronto para fechar", "Pesquisa imóvel", "Encontra concorrente"],
    winOutcome: "Você captura a oportunidade",
    loseOutcome: "A oportunidade vai embora",
  },
  demand: {
    bars: [
      { label: "Venda", value: 90 },
      { label: "Aluguel", value: 75 },
      { label: "Lançamentos", value: 58 },
      { label: "Comercial", value: 40 },
    ],
    totalSearches: "+2.100",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "05 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Milhares de pesquisas por imóveis na sua região todos os meses.",
      "Muitos compradores nunca encontram sua imobiliária.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "imobiliária",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua imobiliária",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, imobiliárias da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Imobiliária ou Segmento",
    eyebrow: "Análise Gratuita",
    title: "Descubra quantas pessoas estão buscando",
    titleHighlight: "imóveis na sua região.",
    subtitle:
      "Receba uma análise personalizada da demanda local — e entenda se sua imobiliária está aparecendo no momento certo.",
    submitLabel: "Quero minha análise de mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
  },
});

export const contabilidadeSegment = createSegmentConfig({
  slug: "contabilidade",
  name: "Contabilidade",
  hubLabel: "Contabilidade",
  icon: Calculator,
  accentColor: "oklch(0.68 0.1 180)",
  accentSoft: "oklch(0.68 0.1 180 / 0.12)",
  seo: {
    title: "Raise One — Seu escritório contábil deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para contadores e escritórios contábeis. Descubra quantos empresários em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Seu escritório contábil deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Empresários da sua região pesquisam no Google por contadores e serviços contábeis. Se você não aparece, esses clientes contratam outro escritório.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Sem contrato",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
    ],
    monthlySearches: "+720",
  },
  visibility: {
    searchExamples: [
      "Contador MEI",
      "Abertura de empresa",
      "Escritório contábil",
      "Contabilidade online",
      "Contador perto de mim",
    ],
    ctaQuestion: "Quando pesquisam, seu escritório aparece?",
    businessType: "escritório",
    eyebrow: "01 — O Problema",
    title: "A maioria dos escritórios não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "equipe qualificada",
      "atendimento ágil",
      "conformidade fiscal",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu escritório.",
  },
  invisibleClient: { searchQuery: "contador MEI" },
  demand: {
    bars: [
      { label: "MEI", value: 78 },
      { label: "Abertura", value: 65 },
      { label: "Fiscal", value: 52 },
      { label: "Folha", value: 38 },
    ],
    totalSearches: "+720",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "04 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Empresários buscam contadores todos os dias na sua região.",
      "Muitos nunca encontram seu escritório.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "contador",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu escritório",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, escritórios da sua região estão aparecendo quando empresários procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Escritório ou Especialidade",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades seu escritório está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite gratuitamente uma análise da sua região e descubra como potenciais clientes estão encontrando seus concorrentes.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const energiaSolarSegment = createSegmentConfig({
  slug: "energia-solar",
  name: "Energia Solar",
  hubLabel: "Energia Solar",
  icon: Sun,
  accentColor: "oklch(0.78 0.16 85)",
  accentSoft: "oklch(0.78 0.16 85 / 0.12)",
  seo: {
    title: "Raise One — Sua empresa solar deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para empresas de energia solar. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Sua empresa de energia solar deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Proprietários da sua região pesquisam no Google por energia solar e instalação de painéis. Se você não aparece, esses clientes fecham com a concorrência.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Sem contrato",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
    ],
    monthlySearches: "+1.200",
  },
  visibility: {
    searchExamples: [
      "Energia solar residencial",
      "Painel solar preço",
      "Instalação fotovoltaica",
      "Energia solar empresarial",
      "Financiamento solar",
    ],
    ctaQuestion: "Quando pesquisam, sua empresa aparece?",
    businessType: "empresa",
    eyebrow: "01 — O Problema",
    title: "A maioria das empresas não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "equipe técnica qualificada",
      "projetos bem executados",
      "suporte pós-venda",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua empresa.",
  },
  invisibleClient: { searchQuery: "energia solar residencial" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como proprietários",
    titleHighlight: "escolhem energia solar no Google",
    steps: [
      { label: "Proprietário pesquisa economia", icon: ScanSearch },
      { label: "Busca no Google", icon: Search },
      { label: "Compara integradores locais", icon: Globe },
      { label: "Solicita orçamento", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda visita técnica", icon: CalendarCheck },
      { label: "Fecha instalação", icon: UserCheck },
    ],
    instagramNote: "A maioria das integradoras depende só de indicação e feiras.",
    googleNote: "Mas a maioria dos proprietários inicia a busca por energia solar no Google.",
  },
  demand: {
    bars: [
      { label: "Residencial", value: 86 },
      { label: "Comercial", value: 68 },
      { label: "Rural", value: 52 },
      { label: "Manutenção", value: 35 },
    ],
    totalSearches: "+1.200",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "04 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "A busca por energia solar cresce todos os meses na sua região.",
      "Muitos proprietários nunca encontram sua empresa.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "energia solar",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua empresa",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, empresas da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Empresa ou Segmento",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades sua empresa está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite gratuitamente uma análise da sua região e descubra como potenciais clientes estão encontrando seus concorrentes.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const construcaoSegment = createSegmentConfig({
  slug: "construcao",
  name: "Construção",
  hubLabel: "Construção e Reformas",
  icon: Hammer,
  accentColor: "oklch(0.66 0.12 55)",
  accentSoft: "oklch(0.66 0.12 55 / 0.12)",
  seo: {
    title: "Raise One — Sua construtora deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para construtoras e reformadoras. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Sua empresa de construção deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Proprietários da sua região pesquisam no Google por reformas e construção. Se você não aparece, esses projetos vão para a concorrência.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Sem contrato",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
    ],
    monthlySearches: "+1.400",
  },
  visibility: {
    searchExamples: [
      "Reforma de apartamento",
      "Construção de casas",
      "Pedreiro qualificado",
      "Reforma de cozinha",
      "Empresa de reformas",
    ],
    ctaQuestion: "Quando pesquisam, sua empresa aparece?",
    businessType: "empresa",
    eyebrow: "01 — O Problema",
    title: "A maioria das empresas não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "obras bem executadas",
      "equipe qualificada",
      "prazos cumpridos",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua empresa.",
  },
  invisibleClient: { searchQuery: "reforma de apartamento" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como proprietários",
    titleHighlight: "contratam obras no Google",
    steps: [
      { label: "Proprietário precisa reformar", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara empresas locais", icon: Globe },
      { label: "Analisa portfólio e avaliações", icon: MousePointerClick },
      { label: "Solicita orçamento", icon: MessageSquare },
      { label: "Agenda visita técnica", icon: CalendarCheck },
      { label: "Fecha o projeto", icon: UserCheck },
    ],
    instagramNote: "A maioria das construtoras depende só de indicação e obra passada.",
    googleNote: "Mas a maioria dos proprietários busca reforma e construção no Google.",
  },
  demand: {
    bars: [
      { label: "Reformas", value: 84 },
      { label: "Construção", value: 70 },
      { label: "Acabamento", value: 55 },
      { label: "Manutenção", value: 42 },
    ],
    totalSearches: "+1.400",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "04 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Proprietários buscam reformas e construção todos os dias na sua região.",
      "Muitos nunca encontram sua empresa.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "reforma apartamento",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua empresa",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, empresas da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Empresa ou Especialidade",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades sua empresa está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite gratuitamente uma análise da sua região e descubra como potenciais clientes estão encontrando seus concorrentes.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const servicosLocaisSegment = createSegmentConfig({
  slug: "servicos-locais",
  name: "Serviços Locais",
  hubLabel: "Serviços Locais",
  icon: Wrench,
  accentColor: "oklch(0.68 0.14 280)",
  accentSoft: "oklch(0.68 0.14 280 / 0.12)",
  seo: {
    title: "Raise One — Seu negócio local deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para prestadores de serviços locais. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Seu negócio local deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Todos os dias, pessoas da sua região pesquisam no Google por serviços que você oferece. Se você não aparece, esses clientes contratam a concorrência.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Sem contrato",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
    ],
    monthlySearches: "+1.100",
  },
  visibility: {
    searchExamples: [
      "Encanador perto de mim",
      "Eletricista 24h",
      "Limpeza residencial",
      "Manutenção predial",
      "Serviços domésticos",
    ],
    ctaQuestion: "Quando pesquisam, seu negócio aparece?",
    businessType: "negócio",
    eyebrow: "01 — O Problema",
    title: "A maioria dos negócios não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "serviço de qualidade",
      "profissionais confiáveis",
      "preço justo",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu negócio.",
  },
  invisibleClient: { searchQuery: "encanador perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como clientes",
    titleHighlight: "contratam serviços locais no Google",
    steps: [
      { label: "Pessoa precisa de um serviço", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara profissionais próximos", icon: Globe },
      { label: "Vê avaliações e disponibilidade", icon: MousePointerClick },
      { label: "Liga ou envia mensagem", icon: MessageSquare },
      { label: "Agenda o atendimento", icon: CalendarCheck },
      { label: "Contrata e recomenda", icon: UserCheck },
    ],
    instagramNote: "A maioria dos prestadores depende só de indicação e grupos locais.",
    googleNote: "Mas a maioria das pessoas busca encanador, eletricista e serviços no Google.",
  },
  demand: {
    bars: [
      { label: "Manutenção", value: 80 },
      { label: "Reparos", value: 68 },
      { label: "Instalação", value: 54 },
      { label: "Emergência", value: 46 },
    ],
    totalSearches: "+1.100",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "04 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Pessoas buscam serviços locais todos os dias na sua região.",
      "Muitos nunca encontram seu negócio.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "encanador",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu negócio",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, empresas da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Negócio ou Serviço",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades seu negócio está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite gratuitamente uma análise da sua região e descubra como potenciais clientes estão encontrando seus concorrentes.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const financeiroSegment = createSegmentConfig({
  slug: "financeiro",
  name: "Financeiro",
  hubLabel: "Serviços Financeiros",
  icon: Landmark,
  accentColor: "oklch(0.64 0.12 160)",
  accentSoft: "oklch(0.64 0.12 160 / 0.12)",
  seo: {
    title: "Raise One — Seu negócio financeiro deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para corretoras, consultorias e empresas do setor financeiro. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Sua empresa financeira deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Pessoas da sua região pesquisam no Google por seguros, crédito e planejamento financeiro. Se você não aparece, esses clientes fecham com a concorrência.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.200",
  },
  visibility: {
    searchExamples: [
      "Corretor de seguros",
      "Empréstimo consignado",
      "Planejamento financeiro",
      "Financiamento imobiliário",
      "Consórcio",
    ],
    ctaQuestion: "Quando pesquisam, sua empresa aparece?",
    businessType: "empresa",
    eyebrow: "01 — O Problema",
    title: "A maioria das empresas financeiras não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "consultores experientes",
      "produtos competitivos",
      "atendimento consultivo",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua empresa.",
  },
  invisibleClient: { searchQuery: "corretor de seguros perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como novos clientes",
    titleHighlight: "encontram serviços financeiros no Google",
    steps: [
      { label: "Pessoa busca crédito ou seguro", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara opções locais", icon: Globe },
      { label: "Analisa propostas e avaliações", icon: MousePointerClick },
      { label: "Solicita contato", icon: MessageSquare },
      { label: "Agenda reunião", icon: CalendarCheck },
      { label: "Fecha contrato", icon: UserCheck },
    ],
    instagramNote: "A maioria tenta captar clientes apenas por indicação.",
    googleNote: "Mas a maioria inicia a busca por crédito e seguros no Google.",
  },
  demand: {
    bars: [
      { label: "Seguros", value: 78 },
      { label: "Crédito", value: 65 },
      { label: "Consórcio", value: 52 },
      { label: "Consultoria", value: 40 },
    ],
    totalSearches: "+1.200",
  },
  fomo: {
    searchQuery: "corretor de seguros",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua empresa",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, corretoras e consultorias da sua região estão aparecendo quando clientes procuram seguros, crédito e planejamento financeiro.",
  },
  form: {
    businessFieldLabel: "Empresa ou Serviço Financeiro",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades sua empresa está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite uma análise da demanda por serviços financeiros na sua região — e veja se você aparece quando o cliente está pronto para contratar.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const automotivoSegment = createSegmentConfig({
  slug: "automotivo",
  name: "Automotivo",
  hubLabel: "Automotivo",
  icon: Car,
  accentColor: "oklch(0.58 0.14 250)",
  accentSoft: "oklch(0.58 0.14 250 / 0.12)",
  seo: {
    title: "Raise One — Sua oficina deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para oficinas, auto centers e serviços automotivos. Descubra quantos clientes em potencial estão indo para a concorrência.",
  },
  hero: {
    title: "Seu negócio automotivo deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Motoristas da sua região pesquisam no Google por oficinas, funilaria e serviços automotivos. Se você não aparece, eles levam o carro para outro lugar.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.600",
  },
  visibility: {
    searchExamples: [
      "Oficina mecânica",
      "Funilaria e pintura",
      "Estética automotiva",
      "Guincho 24 horas",
      "Auto elétrica",
    ],
    ctaQuestion: "Quando pesquisam, sua oficina aparece?",
    businessType: "oficina",
    eyebrow: "01 — O Problema",
    title: "A maioria das oficinas não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "mecânicos experientes",
      "serviço ágil",
      "preço justo",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua oficina.",
  },
  invisibleClient: { searchQuery: "oficina mecânica perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como motoristas",
    titleHighlight: "encontram oficinas no Google",
    steps: [
      { label: "Motorista precisa de serviço", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara oficinas próximas", icon: Globe },
      { label: "Vê avaliações e preços", icon: MousePointerClick },
      { label: "Liga ou envia mensagem", icon: MessageSquare },
      { label: "Agenda o serviço", icon: CalendarCheck },
      { label: "Torna-se cliente", icon: UserCheck },
    ],
    instagramNote: "A maioria das oficinas depende só de indicação e passagem.",
    googleNote: "Mas a maioria dos motoristas busca oficina e guincho no Google.",
  },
  demand: {
    bars: [
      { label: "Mecânica", value: 86 },
      { label: "Funilaria", value: 62 },
      { label: "Estética auto", value: 54 },
      { label: "Guincho", value: 48 },
    ],
    totalSearches: "+1.600",
  },
  fomo: {
    searchQuery: "oficina mecânica",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua oficina",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, oficinas da sua região estão aparecendo quando motoristas procuram mecânica, funilaria e serviços automotivos.",
  },
  form: {
    businessFieldLabel: "Oficina ou Serviço Automotivo",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantos motoristas da sua região",
    titleHighlight: "não estão encontrando você?",
    subtitle:
      "Solicite uma análise da demanda por serviços automotivos — e veja se sua oficina aparece no momento da busca.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const educacaoSegment = createSegmentConfig({
  slug: "educacao",
  name: "Educação",
  hubLabel: "Educação",
  icon: GraduationCap,
  accentColor: "oklch(0.62 0.14 300)",
  accentSoft: "oklch(0.62 0.14 300 / 0.12)",
  seo: {
    title: "Raise One — Sua escola deveria estar recebendo mais matrículas",
    description:
      "Diagnóstico gratuito para escolas, cursos e autoescolas. Descubra quantas famílias em potencial estão escolhendo a concorrência na sua região.",
  },
  hero: {
    title: "Sua escola deveria estar",
    titleHighlight: "recebendo mais matrículas.",
    subtitle:
      "Famílias da sua região pesquisam no Google por escolas, cursos e reforço escolar. Se você não aparece, essas matrículas vão para outro lugar.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.300",
  },
  visibility: {
    searchExamples: [
      "Escola particular",
      "Curso de inglês",
      "Reforço escolar",
      "Autoescola",
      "Curso preparatório",
    ],
    ctaQuestion: "Quando pesquisam, sua escola aparece?",
    businessType: "escola",
    eyebrow: "01 — O Problema",
    title: "A maioria das escolas não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "professores qualificados",
      "metodologia sólida",
      "estrutura adequada",
      "famílias satisfeitas",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua escola.",
  },
  invisibleClient: { searchQuery: "escola particular perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como famílias",
    titleHighlight: "escolhem escolas no Google",
    steps: [
      { label: "Família busca escola ou curso", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara opções da região", icon: Globe },
      { label: "Visita site e avaliações", icon: MousePointerClick },
      { label: "Solicita informações", icon: MessageSquare },
      { label: "Agenda visita ou prova", icon: CalendarCheck },
      { label: "Realiza matrícula", icon: UserCheck },
    ],
    instagramNote: "A maioria das escolas depende só de indicação e panfletos.",
    googleNote: "Mas a maioria das famílias inicia a busca por escolas e cursos no Google.",
  },
  demand: {
    bars: [
      { label: "Escolas", value: 80 },
      { label: "Cursos", value: 68 },
      { label: "Reforço", value: 55 },
      { label: "Autoescola", value: 42 },
    ],
    totalSearches: "+1.300",
  },
  fomo: {
    searchQuery: "escola particular",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua escola",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, escolas e cursos da sua região estão aparecendo quando famílias procuram matrículas e reforço escolar.",
  },
  form: {
    businessFieldLabel: "Escola ou Curso",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas matrículas sua escola está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite uma análise da demanda por educação na sua região — e veja se você aparece quando a família está pronta para decidir.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const alimentacaoSegment = createSegmentConfig({
  slug: "alimentacao",
  name: "Alimentação",
  hubLabel: "Alimentação",
  icon: UtensilsCrossed,
  accentColor: "oklch(0.68 0.16 45)",
  accentSoft: "oklch(0.68 0.16 45 / 0.12)",
  seo: {
    title: "Raise One — Seu restaurante deveria estar recebendo mais pedidos",
    description:
      "Diagnóstico gratuito para restaurantes, delivery e food service. Descubra quantos clientes em potencial estão pedindo da concorrência na sua região.",
  },
  hero: {
    title: "Seu negócio de alimentação deveria estar",
    titleHighlight: "recebendo mais pedidos.",
    subtitle:
      "Pessoas da sua região pesquisam no Google por restaurantes, delivery e opções para comer. Se você não aparece, esses pedidos vão para a concorrência.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+2.100",
  },
  visibility: {
    searchExamples: [
      "Restaurante perto de mim",
      "Delivery de comida",
      "Hamburgueria",
      "Pizzaria delivery",
      "Marmitaria",
    ],
    ctaQuestion: "Quando pesquisam, seu restaurante aparece?",
    businessType: "restaurante",
    eyebrow: "01 — O Problema",
    title: "A maioria dos restaurantes não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "comida de qualidade",
      "atendimento ágil",
      "ambiente agradável",
      "clientes fiéis",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu restaurante.",
  },
  invisibleClient: { searchQuery: "restaurante perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como clientes",
    titleHighlight: "escolhem onde comer no Google",
    steps: [
      { label: "Pessoa decide onde comer", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara restaurantes próximos", icon: Globe },
      { label: "Vê cardápio e avaliações", icon: MousePointerClick },
      { label: "Faz pedido ou reserva", icon: MessageSquare },
      { label: "Confirma entrega ou mesa", icon: CalendarCheck },
      { label: "Torna-se cliente recorrente", icon: UserCheck },
    ],
    instagramNote: "A maioria dos restaurantes depende só de iFood e indicação.",
    googleNote: "Mas muitos clientes ainda buscam restaurante e delivery direto no Google.",
  },
  demand: {
    bars: [
      { label: "Delivery", value: 92 },
      { label: "Restaurantes", value: 85 },
      { label: "Lanches", value: 72 },
      { label: "Marmitas", value: 58 },
    ],
    totalSearches: "+2.100",
  },
  fomo: {
    searchQuery: "restaurante",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu restaurante",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, restaurantes da sua região estão aparecendo quando clientes procuram onde comer, delivery e opções locais.",
  },
  form: {
    businessFieldLabel: "Restaurante ou Tipo de Comida",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantos pedidos seu restaurante está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite uma análise da demanda por alimentação na sua região — e veja se você aparece quando o cliente está com fome e pronto para pedir.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const petsSegment = createSegmentConfig({
  slug: "pets",
  name: "Pets",
  hubLabel: "Pets",
  icon: PawPrint,
  accentColor: "oklch(0.66 0.14 145)",
  accentSoft: "oklch(0.66 0.14 145 / 0.12)",
  seo: {
    title: "Raise One — Seu pet shop deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para pet shops, clínicas veterinárias e banho e tosa. Descubra quantos tutores em potencial estão indo para a concorrência na sua região.",
  },
  hero: {
    title: "Seu negócio pet deveria estar",
    titleHighlight: "recebendo mais clientes.",
    subtitle:
      "Todos os dias, tutores da sua região pesquisam no Google por pet shop, veterinário e banho e tosa. Se você não aparece, esses clientes vão para outro lugar.",
    ctaLabel: "Quero analisar meu mercado",
    badge: "Especialistas em crescimento para negócios locais",
    trustItems: [
      "Sem compromisso",
      "Análise personalizada da sua região",
      "Retorno em até 24 horas",
      "Sem linguagem técnica",
    ],
    monthlySearches: "+1.400",
  },
  visibility: {
    searchExamples: [
      "Pet shop perto de mim",
      "Veterinário 24 horas",
      "Banho e tosa",
      "Ração e acessórios",
      "Clínica veterinária",
    ],
    ctaQuestion: "Quando pesquisam, seu pet shop aparece?",
    businessType: "pet shop",
    eyebrow: "01 — O Problema",
    title: "A maioria dos negócios pet não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "cuidado com os animais",
      "profissionais qualificados",
      "produtos de qualidade",
      "tutores satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou seu pet shop.",
  },
  invisibleClient: { searchQuery: "pet shop perto de mim" },
  journey: {
    eyebrow: "03 — A Jornada",
    title: "Como tutores",
    titleHighlight: "encontram serviços pet no Google",
    steps: [
      { label: "Tutor precisa de serviço pet", icon: ScanSearch },
      { label: "Pesquisa no Google", icon: Search },
      { label: "Compara pet shops e clínicas", icon: Globe },
      { label: "Vê avaliações e horários", icon: MousePointerClick },
      { label: "Entra em contato", icon: MessageSquare },
      { label: "Agenda consulta ou banho", icon: CalendarCheck },
      { label: "Torna-se cliente", icon: UserCheck },
    ],
    instagramNote: "A maioria dos pet shops depende só de indicação e Instagram.",
    googleNote: "Mas a maioria dos tutores busca veterinário e pet shop no Google.",
  },
  demand: {
    bars: [
      { label: "Pet shop", value: 82 },
      { label: "Veterinário", value: 74 },
      { label: "Banho e tosa", value: 65 },
      { label: "Ração", value: 52 },
    ],
    totalSearches: "+1.400",
  },
  fomo: {
    searchQuery: "pet shop",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Seu pet shop",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, pet shops e clínicas veterinárias da sua região estão aparecendo quando tutores procuram banho, tosa e atendimento.",
  },
  form: {
    businessFieldLabel: "Pet Shop ou Serviço Pet",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantos tutores da sua região",
    titleHighlight: "não estão encontrando você?",
    subtitle:
      "Solicite uma análise da demanda por serviços pet — e veja se você aparece quando o tutor precisa de atendimento.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});

export const outroSegment = createSegmentConfig({
  slug: "outro",
  name: "Outro",
  hubLabel: "Outro",
  icon: HelpCircle,
  accentColor: "oklch(0.65 0.08 280)",
  accentSoft: "oklch(0.65 0.08 280 / 0.12)",
  seo: {
    title: "Raise One — Seu negócio deveria estar recebendo mais clientes",
    description:
      "Diagnóstico gratuito para negócios locais. Descubra quantos clientes em potencial estão indo para a concorrência na sua região.",
  },
  visibility: {
    searchExamples: [
      "Serviço perto de mim",
      "Melhor empresa da região",
      "Orçamento online",
      "Empresa confiável",
      "Atendimento local",
    ],
    ctaQuestion: "Quando pesquisam, sua empresa aparece?",
    businessType: "empresa",
    eyebrow: "01 — O Problema",
    title: "A maioria dos negócios não tem problema de qualidade.",
    titleMuted: "Tem problema de visibilidade.",
    qualities: [
      "excelente atendimento",
      "profissionais qualificados",
      "boa estrutura",
      "clientes satisfeitos",
    ],
    closingLine: "Mas nada disso importa para quem nunca encontrou sua empresa.",
  },
  invisibleClient: { searchQuery: "serviço perto de mim" },
  demand: {
    bars: [
      { label: "Busca local", value: 75 },
      { label: "Comparativos", value: 62 },
      { label: "Orçamentos", value: 48 },
      { label: "Avaliações", value: 36 },
    ],
    totalSearches: "+850",
    capturedLabel: "Capturado por você",
    availableLabel: "Disponível",
    eyebrow: "04 — A Oportunidade",
    title: "Existe demanda na sua região.",
    titleMuted: "A questão é quem está capturando essa demanda.",
    paragraphs: [
      "Pessoas buscam serviços na sua região todos os dias.",
      "Muitas nunca encontram sua empresa.",
      "Não porque você é pior. Mas porque você não apareceu.",
    ],
  },
  fomo: {
    searchQuery: "serviço local",
    competitors: sharedCompetitors,
    yourBusinessLabel: "Sua empresa",
    notFoundLabel: "não aparece",
    title: "Seus concorrentes já entenderam isso.",
    subtitle:
      "Enquanto você lê esta página, empresas da sua região estão aparecendo quando clientes procuram pelos mesmos serviços que você oferece.",
  },
  form: {
    businessFieldLabel: "Empresa ou Segmento",
    eyebrow: "Diagnóstico Gratuito",
    title: "Quantas oportunidades sua empresa está",
    titleHighlight: "deixando passar hoje?",
    subtitle:
      "Solicite gratuitamente uma análise da sua região e descubra como potenciais clientes estão encontrando seus concorrentes.",
    submitLabel: "Quero analisar meu mercado",
    footerNote: "Sem compromisso · Retorno em até 24 horas",
  },
});
