import { mv } from "./helpers";
import type { MicroverticalDefinition } from "./types";

/** Catálogo completo de microverticais — mapeia negócios para LPs-template */
export const MICROVERTICAL_CATALOG: MicroverticalDefinition[] = [
  // ══════════════════════════════════════════════════════════════
  // BELEZA
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "estetica",
    label: "Clínica de Estética",
    keywords: ["estetica", "estética", "clinica estetica", "clínica estética", "botox", "peeling", "esteticista"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Botox", "Harmonização Facial", "Limpeza de Pele", "Preenchimento", "Depilação a Laser"],
    searches: ["botox {city}", "harmonização facial {city}", "clínica estética perto de mim", "limpeza de pele {city}"],
  }),
  mv({
    id: "harmonizacao-facial",
    label: "Harmonização Facial",
    keywords: ["harmonizacao facial", "harmonização facial", "harmonizacao", "harmonização", "preenchimento labial", "filler"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Harmonização facial", "Preenchimento labial", "Botox", "Rinomodelação", "Bioestimuladores"],
    searches: ["harmonização facial {city}", "preenchimento labial {city}", "harmonização facial perto de mim"],
  }),
  mv({
    id: "barbearia",
    label: "Barbearia",
    keywords: ["barbearia", "barbeiro", "barba", "corte masculino", "barbershop"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "high",
    businessType: "barbearia",
    yourBusinessLabel: "Sua barbearia",
    suggestedServices: ["Corte masculino", "Barba", "Sobrancelha", "Pacote corte + barba", "Design de barba"],
    searches: ["barbearia perto de mim", "corte masculino {city}", "barbeiro {city}", "barba e cabelo {city}"],
  }),
  mv({
    id: "salao",
    label: "Salão de Beleza",
    keywords: ["salao", "salão", "cabeleireiro", "cabeleireira", "hair", "progressiva", "nail designer", "studio de beleza"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "high",
    businessType: "salão",
    yourBusinessLabel: "Seu salão",
    suggestedServices: ["Corte feminino", "Coloração", "Progressiva", "Escova", "Tratamento capilar"],
    searches: ["salão de beleza {city}", "cabeleireiro perto de mim", "progressiva {city}", "salão {city}"],
  }),
  mv({
    id: "manicure",
    label: "Manicure",
    keywords: ["manicure", "manicurista", "nail designer", "unhas", "esmalteria", "nail art"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "high",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Manicure", "Pedicure", "Alongamento de unhas", "Nail art", "Spa dos pés"],
    searches: ["manicure {city}", "nail designer {city}", "manicure perto de mim", "esmalteria {city}"],
  }),
  mv({
    id: "clinica-capilar",
    label: "Clínica Capilar",
    keywords: ["clinica capilar", "clínica capilar", "tratamento capilar", "queda de cabelo", "calvicie", "capilar"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Tratamento capilar", "Queda de cabelo", "Mesoterapia capilar", "PRP capilar", "Avaliação capilar"],
    searches: ["clínica capilar {city}", "tratamento queda de cabelo {city}", "clínica capilar perto de mim"],
  }),
  mv({
    id: "transplante-capilar",
    label: "Transplante Capilar",
    keywords: ["transplante capilar", "implante capilar", "cirurgia capilar", "fue", "fut capilar"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Transplante capilar FUE", "Transplante capilar FUT", "Avaliação capilar", "PRP", "Mesoterapia"],
    searches: ["transplante capilar {city}", "implante capilar {city}", "transplante capilar preço {city}"],
  }),
  mv({
    id: "podologia",
    label: "Podologia",
    keywords: ["podologia", "podologo", "podólogo", "podologa", "podóloga", "pe do atleta", "pé do atleta"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Podologia", "Tratamento de unhas encravadas", "Pé do atleta", "Calosidades", "Micose"],
    searches: ["podólogo {city}", "podologia {city}", "podólogo perto de mim"],
  }),
  mv({
    id: "bronzeamento",
    label: "Bronzeamento",
    keywords: ["bronzeamento", "bronze", "bronze artificial", "auto bronzeamento", "spray tan"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Bronzeamento artificial", "Spray tan", "Bronzeamento a jato", "Pacotes mensais"],
    searches: ["bronzeamento {city}", "bronze artificial {city}", "bronzeamento perto de mim"],
  }),
  mv({
    id: "estudio-tatuagem",
    label: "Estúdio de Tatuagem",
    keywords: ["tatuagem", "tatuador", "tattoo", "estudio de tatuagem", "estúdio de tatuagem", "piercing"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Tatuagem", "Cover-up", "Piercing", "Orçamento personalizado", "Retoque"],
    searches: ["estúdio de tatuagem {city}", "tatuador {city}", "tatuagem perto de mim"],
  }),
  mv({
    id: "lash",
    label: "Lash Designer",
    keywords: ["lash", "cilios", "cílios", "extensao de cilios", "extensão de cílios"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Extensão de cílios", "Volume russo", "Manutenção", "Lash lifting"],
    searches: ["extensão de cílios {city}", "lash designer {city}", "cílios {city}"],
  }),
  mv({
    id: "micropigmentacao",
    label: "Micropigmentação",
    keywords: ["micropigmentacao", "micropigmentação", "sobrancelha", "microblading"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Micropigmentação", "Microblading", "Design de sobrancelha"],
    searches: ["micropigmentação {city}", "microblading {city}", "sobrancelha definitiva {city}"],
  }),
  mv({
    id: "depilacao",
    label: "Depilação",
    keywords: ["depilacao", "depilação", "depiladora", "depilacao a laser", "depilação a laser", "laser"],
    macroCategory: "beleza",
    templateSlug: "estetica",
    priority: "medium",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Depilação a laser", "Depilação definitiva", "Depilação com cera"],
    searches: ["depilação a laser {city}", "depilação definitiva {city}", "depilação {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // SAÚDE
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "medico-particular",
    label: "Médico Particular",
    keywords: ["medico particular", "médico particular", "consulta medica", "consulta médica", "clinico geral", "clínico geral"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta particular", "Check-up", "Exames", "Retorno", "Telemedicina"],
    searches: ["médico particular {city}", "consulta médica {city}", "médico perto de mim"],
  }),
  mv({
    id: "clinica-medica",
    label: "Clínica Médica",
    keywords: ["clinica medica", "clínica médica", "clinica geral", "clínica geral", "policlinica", "policlínica"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Consultas", "Exames", "Check-up", "Especialidades", "Convênios"],
    searches: ["clínica médica {city}", "clínica médica perto de mim", "consultório médico {city}"],
  }),
  mv({
    id: "dermatologista",
    label: "Dermatologista",
    keywords: ["dermatologista", "dermatologia", "dermato", "pele", "acne", "melasma"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta dermatológica", "Tratamento de acne", "Melasma", "Mapeamento de pintas", "Peeling médico"],
    searches: ["dermatologista {city}", "dermatologista perto de mim", "dermatologia {city}"],
  }),
  mv({
    id: "ginecologista",
    label: "Ginecologista",
    keywords: ["ginecologista", "ginecologia", "gineco", "obstetra", "obstetrícia", "pre natal", "pré-natal"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta ginecológica", "Pré-natal", "Preventivo", "Ultrassom", "Planejamento familiar"],
    searches: ["ginecologista {city}", "ginecologista perto de mim", "obstetra {city}"],
  }),
  mv({
    id: "cardiologista",
    label: "Cardiologista",
    keywords: ["cardiologista", "cardiologia", "cardio", "coracao", "coração", "ecocardiograma"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta cardiológica", "Ecocardiograma", "Teste ergométrico", "Holter", "Check-up cardíaco"],
    searches: ["cardiologista {city}", "cardiologista perto de mim", "cardiologia {city}"],
  }),
  mv({
    id: "ortopedista",
    label: "Ortopedista",
    keywords: ["ortopedista", "ortopedia", "ortopedico", "ortopédico", "joelho", "coluna", "fratura"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta ortopédica", "Joelho", "Coluna", "Ombro", "Cirurgia ortopédica"],
    searches: ["ortopedista {city}", "ortopedista perto de mim", "ortopedia {city}"],
  }),
  mv({
    id: "oftalmologista",
    label: "Oftalmologista",
    keywords: ["oftalmologista", "oftalmologia", "oculista", "olhos", "catarata", "grau"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta oftalmológica", "Exame de vista", "Cirurgia de catarata", "Mapeamento de retina", "Lentes"],
    searches: ["oftalmologista {city}", "oftalmologista perto de mim", "oculista {city}"],
  }),
  mv({
    id: "dentista",
    label: "Dentista",
    keywords: ["dentista", "odontologo", "odontólogo", "consultorio odontologico", "consultório odontológico"],
    macroCategory: "saude",
    templateSlug: "dentista",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Implante", "Clareamento", "Ortodontia", "Limpeza dental", "Canal"],
    searches: ["dentista {city}", "dentista perto de mim", "consultório odontológico {city}"],
  }),
  mv({
    id: "clinica-odontologica",
    label: "Clínica Odontológica",
    keywords: ["clinica odontologica", "clínica odontológica", "odontologia", "odonto", "ortodontista", "ortodontia", "implante dentario", "implante dentário"],
    macroCategory: "saude",
    templateSlug: "dentista",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Implantes", "Ortodontia", "Clareamento", "Próteses", "Harmonização orofacial"],
    searches: ["clínica odontológica {city}", "implante dentário {city}", "ortodontia {city}"],
  }),
  mv({
    id: "fisioterapia",
    label: "Fisioterapia",
    keywords: ["fisioterapia", "fisioterapeuta", "fisio", "rpg", "pilates clinico", "pilates clínico"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Fisioterapia", "RPG", "Pilates", "Reabilitação", "Fisioterapia esportiva"],
    searches: ["fisioterapia {city}", "fisioterapeuta perto de mim", "fisio {city}"],
  }),
  mv({
    id: "fonoaudiologo",
    label: "Fonoaudiólogo",
    keywords: ["fonoaudiologo", "fonoaudiólogo", "fonoaudiologia", "fono", "audiologia", "terapia da fala"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Fonoaudiologia", "Terapia da fala", "Audiometria", "Disfagia", "Linguagem infantil"],
    searches: ["fonoaudiólogo {city}", "fonoaudiologia {city}", "fonoaudiólogo perto de mim"],
  }),
  mv({
    id: "terapia-ocupacional",
    label: "Terapia Ocupacional",
    keywords: ["terapia ocupacional", "terapeuta ocupacional", "to", "reabilitacao", "reabilitação"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Terapia ocupacional", "Reabilitação", "Integração sensorial", "Atendimento infantil", "Avaliação funcional"],
    searches: ["terapia ocupacional {city}", "terapeuta ocupacional {city}", "terapia ocupacional perto de mim"],
  }),
  mv({
    id: "quiropraxia",
    label: "Quiropraxia",
    keywords: ["quiropraxia", "quiroprata", "quiro", "coluna", "dor nas costas", "ajuste quiropratico"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Quiropraxia", "Ajuste quiroprático", "Dor nas costas", "Hérnia de disco", "Postura"],
    searches: ["quiropraxia {city}", "quiroprata {city}", "quiropraxia perto de mim"],
  }),
  mv({
    id: "acupuntura",
    label: "Acupuntura",
    keywords: ["acupuntura", "acupunturista", "agulhas", "medicina chinesa", "auriculoterapia"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Acupuntura", "Auriculoterapia", "Dor crônica", "Ansiedade", "Emagrecimento"],
    searches: ["acupuntura {city}", "acupunturista {city}", "acupuntura perto de mim"],
  }),
  mv({
    id: "home-care",
    label: "Home Care",
    keywords: ["home care", "homecare", "atendimento domiciliar", "cuidador", "enfermagem domiciliar", "idoso"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Home care", "Enfermagem domiciliar", "Cuidador de idosos", "Fisioterapia domiciliar", "Medicação"],
    searches: ["home care {city}", "atendimento domiciliar {city}", "home care perto de mim"],
  }),
  mv({
    id: "exames-laboratoriais",
    label: "Exames Laboratoriais",
    keywords: ["laboratorio", "laboratório", "exames laboratoriais", "coleta de sangue", "analises clinicas", "análises clínicas"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "laboratório",
    yourBusinessLabel: "Seu laboratório",
    suggestedServices: ["Exames de sangue", "Check-up laboratorial", "Coleta domiciliar", "Exames de rotina", "Resultados online"],
    searches: ["laboratório {city}", "exames laboratoriais {city}", "laboratório perto de mim"],
  }),
  mv({
    id: "clinica-imagem",
    label: "Clínica de Imagem",
    keywords: ["clinica de imagem", "clínica de imagem", "raio x", "raio-x", "ultrassom", "ressonancia", "ressonância", "tomografia"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Ultrassom", "Ressonância magnética", "Tomografia", "Raio-X", "Mamografia"],
    searches: ["clínica de imagem {city}", "ultrassom {city}", "ressonância magnética {city}"],
  }),
  mv({
    id: "psicologo",
    label: "Psicólogo",
    keywords: ["psicologo", "psicólogo", "psicologia", "terapia", "terapeuta", "psicanalise", "psicanálise"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "high",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Terapia individual", "Terapia de casal", "Psicologia online", "Terapia infantil", "Ansiedade"],
    searches: ["psicólogo {city}", "terapia perto de mim", "psicólogo online {city}"],
  }),
  mv({
    id: "nutricionista",
    label: "Nutricionista",
    keywords: ["nutricionista", "nutricao", "nutrição", "nutricionismo", "nutri", "reeducacao alimentar"],
    macroCategory: "saude",
    templateSlug: "clinica",
    priority: "medium",
    businessType: "consultório",
    yourBusinessLabel: "Seu consultório",
    suggestedServices: ["Consulta nutricional", "Reeducação alimentar", "Emagrecimento", "Nutrição esportiva", "Plano alimentar"],
    searches: ["nutricionista {city}", "nutri perto de mim", "nutricionista online {city}"],
  }),
  // ══════════════════════════════════════════════════════════════
  // PETS
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "pet-shop",
    label: "Pet Shop",
    keywords: ["pet shop", "petshop", "loja de pets", "pet store", "aquarismo"],
    macroCategory: "pets",
    templateSlug: "pets",
    priority: "high",
    businessType: "pet shop",
    yourBusinessLabel: "Seu pet shop",
    suggestedServices: ["Banho e tosa", "Rações e acessórios", "Consulta veterinária", "Vacinas", "Hospedagem"],
    searches: ["pet shop perto de mim", "pet shop {city}", "loja de pets {city}"],
  }),
  mv({
    id: "veterinario",
    label: "Veterinário",
    keywords: ["veterinario", "veterinário", "clinica veterinaria", "clínica veterinária", "vet"],
    macroCategory: "pets",
    templateSlug: "pets",
    heroHighlight: "recebendo mais tutores.",
    priority: "high",
    businessType: "clínica",
    yourBusinessLabel: "Sua clínica",
    suggestedServices: ["Consulta veterinária", "Vacinas", "Cirurgias", "Exames", "Emergência 24h"],
    searches: ["veterinário {city}", "clínica veterinária perto de mim", "veterinário 24 horas {city}"],
  }),
  mv({
    id: "banho-e-tosa",
    label: "Banho e Tosa",
    keywords: ["banho e tosa", "tosa", "pet grooming", "estetica pet", "estética pet"],
    macroCategory: "pets",
    templateSlug: "pets",
    priority: "medium",
    businessType: "pet shop",
    yourBusinessLabel: "Seu pet shop",
    suggestedServices: ["Banho", "Tosa", "Hidratação", "Pacotes mensais", "Tosa higiênica"],
    searches: ["banho e tosa {city}", "tosa de cachorro {city}", "banho e tosa perto de mim"],
  }),

  // ══════════════════════════════════════════════════════════════
  // JURÍDICO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "advogado",
    label: "Advogado",
    keywords: ["advogado", "advocacia", "escritorio advocacia", "escritório advocacia", "juridico", "jurídico"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Consultoria jurídica", "Contratos", "Cível", "Empresarial", "Mediação"],
    searches: ["advogado {city}", "advogado perto de mim", "escritório de advocacia {city}"],
  }),
  mv({
    id: "advogado-trabalhista",
    label: "Advogado Trabalhista",
    keywords: ["advogado trabalhista", "trabalhista", "direito trabalhista", "reclamacao trabalhista", "reclamação trabalhista", "clt"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Reclamação trabalhista", "Rescisão", "Acidente de trabalho", "Assédio moral", "Horas extras"],
    searches: ["advogado trabalhista {city}", "advogado trabalhista perto de mim", "direito trabalhista {city}"],
  }),
  mv({
    id: "advogado-previdenciario",
    label: "Advogado Previdenciário",
    keywords: ["advogado previdenciario", "advogado previdenciário", "previdenciario", "previdenciário", "inss", "aposentadoria", "beneficio inss"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Aposentadoria", "BPC/LOAS", "Auxílio-doença", "Revisão de benefício", "Pensão por morte"],
    searches: ["advogado previdenciário {city}", "advogado INSS {city}", "aposentadoria advogado {city}"],
  }),
  mv({
    id: "advogado-familia",
    label: "Advogado de Família",
    keywords: ["advogado familia", "advogado família", "direito de familia", "direito de família", "divorcio", "divórcio", "pensao alimenticia"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Divórcio", "Pensão alimentícia", "Guarda de filhos", "Inventário", "União estável"],
    searches: ["advogado de família {city}", "advogado divórcio {city}", "direito de família {city}"],
  }),
  mv({
    id: "advogado-imobiliario",
    label: "Advogado Imobiliário",
    keywords: ["advogado imobiliario", "advogado imobiliário", "direito imobiliario", "direito imobiliário", "usucapiao", "usucapião", "despejo"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "medium",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Contratos imobiliários", "Usucapião", "Despejo", "Regularização", "Incorporação"],
    searches: ["advogado imobiliário {city}", "direito imobiliário {city}", "advogado despejo {city}"],
  }),
  mv({
    id: "advogado-criminal",
    label: "Advogado Criminal",
    keywords: ["advogado criminal", "criminalista", "direito penal", "defesa criminal", "habeas corpus"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Defesa criminal", "Habeas corpus", "Audiência de custódia", "Júri", "Crimes de trânsito"],
    searches: ["advogado criminal {city}", "criminalista {city}", "advogado criminalista {city}"],
  }),
  mv({
    id: "correspondente-juridico",
    label: "Correspondente Jurídico",
    keywords: ["correspondente juridico", "correspondente jurídico", "diligencia juridica", "diligência jurídica", "protocolo judicial"],
    macroCategory: "juridico",
    templateSlug: "advogado",
    priority: "medium",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Diligências", "Protocolo judicial", "Cópias de processos", "Audiências", "Localização de partes"],
    searches: ["correspondente jurídico {city}", "diligência jurídica {city}", "correspondente jurídico perto de mim"],
  }),

  // ══════════════════════════════════════════════════════════════
  // FINANCEIRO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "contabilidade",
    label: "Contabilidade",
    keywords: ["contador", "contabilidade", "contábil", "mei", "escritorio contabil", "escritório contábil"],
    macroCategory: "financeiro",
    templateSlug: "contabilidade",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["MEI", "Abertura de empresa", "Fiscal", "Folha de pagamento", "Declaração IR"],
    searches: ["contador {city}", "contabilidade MEI {city}", "escritório contábil {city}"],
  }),
  mv({
    id: "consultoria-financeira",
    label: "Consultoria Financeira",
    keywords: ["consultoria financeira", "consultor financeiro", "planejamento financeiro pessoal", "educacao financeira"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "medium",
    businessType: "consultoria",
    yourBusinessLabel: "Sua consultoria",
    suggestedServices: ["Planejamento financeiro", "Organização de finanças", "Investimentos", "Aposentadoria", "Consultoria empresarial"],
    searches: ["consultoria financeira {city}", "consultor financeiro {city}", "planejamento financeiro {city}"],
  }),
  mv({
    id: "planejamento-financeiro",
    label: "Planejamento Financeiro",
    keywords: ["planejamento financeiro", "planejador financeiro", "cfp", "investimentos", "patrimonio", "patrimônio"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "medium",
    businessType: "consultoria",
    yourBusinessLabel: "Sua consultoria",
    suggestedServices: ["Planejamento patrimonial", "Investimentos", "Aposentadoria", "Sucessão", "Proteção financeira"],
    searches: ["planejamento financeiro {city}", "planejador financeiro {city}", "consultor de investimentos {city}"],
  }),
  mv({
    id: "corretor-seguros",
    label: "Corretor de Seguros",
    keywords: ["corretor de seguros", "seguros", "corretora de seguros", "seguro de vida", "seguro auto", "seguro residencial"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "high",
    businessType: "corretora",
    yourBusinessLabel: "Sua corretora",
    suggestedServices: ["Seguro de vida", "Seguro auto", "Seguro residencial", "Seguro empresarial", "Plano de saúde"],
    searches: ["corretor de seguros {city}", "seguro de vida {city}", "corretora de seguros {city}"],
  }),
  mv({
    id: "consorcio",
    label: "Consórcio",
    keywords: ["consorcio", "consórcio", "carta de credito", "carta de crédito", "consorcio imovel", "consórcio imóvel", "consorcio carro"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Consórcio de imóvel", "Consórcio de carro", "Carta contemplada", "Simulação", "Administradora"],
    searches: ["consórcio {city}", "consórcio de imóvel {city}", "consórcio de carro {city}"],
  }),
  mv({
    id: "credito-imobiliario",
    label: "Crédito Imobiliário",
    keywords: ["credito imobiliario", "crédito imobiliário", "financiamento imobiliario", "financiamento imobiliário", "financiamento casa", "financiamento apartamento"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Financiamento imobiliário", "Simulação de crédito", "Refinanciamento", "Portabilidade", "Análise de crédito"],
    searches: ["crédito imobiliário {city}", "financiamento imobiliário {city}", "financiamento apartamento {city}"],
  }),
  mv({
    id: "emprestimo-consignado",
    label: "Empréstimo Consignado",
    keywords: ["emprestimo consignado", "empréstimo consignado", "consignado", "credito consignado", "crédito consignado", "emprestimo inss"],
    macroCategory: "financeiro",
    templateSlug: "financeiro",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Empréstimo consignado", "Refinanciamento", "Portabilidade", "Antecipação FGTS", "Crédito pessoal"],
    searches: ["empréstimo consignado {city}", "consignado INSS {city}", "crédito consignado {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // IMOBILIÁRIO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "imobiliaria",
    label: "Imobiliária",
    keywords: ["imobiliaria", "imobiliária", "corretora de imoveis", "corretora de imóveis"],
    macroCategory: "imoveis",
    templateSlug: "imobiliaria",
    priority: "high",
    businessType: "imobiliária",
    yourBusinessLabel: "Sua imobiliária",
    suggestedServices: ["Venda", "Aluguel", "Lançamentos", "Comercial", "Avaliação"],
    searches: ["imobiliária {city}", "apartamento à venda {city}", "imobiliária perto de mim"],
  }),
  mv({
    id: "corretor-imoveis",
    label: "Corretor de Imóveis",
    keywords: ["corretor", "corretora", "corretor de imoveis", "corretor de imóveis", "creci", "imovel", "imóvel", "apartamento"],
    macroCategory: "imoveis",
    templateSlug: "imobiliaria",
    priority: "high",
    businessType: "corretor",
    yourBusinessLabel: "Seu negócio",
    suggestedServices: ["Venda de imóveis", "Aluguel", "Captação", "Avaliação", "Consultoria imobiliária"],
    searches: ["corretor de imóveis {city}", "apartamento à venda {city}", "corretor {city}"],
  }),
  mv({
    id: "administracao-condominios",
    label: "Administração de Condomínios",
    keywords: ["administracao de condominios", "administração de condomínios", "sindico profissional", "síndico profissional", "administradora de condominio"],
    macroCategory: "imoveis",
    templateSlug: "imobiliaria",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Administração predial", "Síndico profissional", "Gestão financeira", "Assembleias", "Manutenção predial"],
    searches: ["administração de condomínios {city}", "síndico profissional {city}", "administradora de condomínio {city}"],
  }),
  mv({
    id: "avaliacao-imobiliaria",
    label: "Avaliação Imobiliária",
    keywords: ["avaliacao imobiliaria", "avaliação imobiliária", "avaliador de imoveis", "avaliador de imóveis", "laudo imobiliario"],
    macroCategory: "imoveis",
    templateSlug: "imobiliaria",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Avaliação de imóveis", "Laudo técnico", "Avaliação para financiamento", "Perícia", "Vistoria"],
    searches: ["avaliação imobiliária {city}", "avaliador de imóveis {city}", "laudo imobiliário {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // CASA E CONSTRUÇÃO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "construcao",
    label: "Construção e Reformas",
    keywords: ["construcao", "construção", "reforma", "obra", "pedreiro", "empreiteira"],
    macroCategory: "construcao",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Reformas", "Construção", "Acabamento", "Manutenção", "Orçamento"],
    searches: ["reforma apartamento {city}", "construção {city}", "empresa de reformas {city}"],
  }),
  mv({
    id: "arquitetura",
    label: "Arquitetura",
    keywords: ["arquitetura", "arquiteto", "arquiteta", "projeto arquitetonico", "projeto arquitetônico", "design de interiores"],
    macroCategory: "construcao",
    templateSlug: "construcao",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Projeto arquitetônico", "Reforma", "Regularização", "Consultoria", "Acompanhamento de obra"],
    searches: ["arquiteto {city}", "projeto arquitetônico {city}", "arquitetura {city}"],
  }),
  mv({
    id: "engenharia-civil",
    label: "Engenharia Civil",
    keywords: ["engenharia civil", "engenheiro civil", "engenheiro", "laudo estrutural", "fiscalizacao de obra"],
    macroCategory: "construcao",
    templateSlug: "construcao",
    priority: "high",
    businessType: "escritório",
    yourBusinessLabel: "Seu escritório",
    suggestedServices: ["Projeto estrutural", "Laudo técnico", "Fiscalização de obra", "Regularização", "ART"],
    searches: ["engenheiro civil {city}", "engenharia civil {city}", "laudo estrutural {city}"],
  }),
  mv({
    id: "designer-interiores",
    label: "Designer de Interiores",
    keywords: ["designer de interiores", "design de interiores", "decoracao", "decoração", "decorador", "decoradora"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "estúdio",
    yourBusinessLabel: "Seu estúdio",
    suggestedServices: ["Projeto de interiores", "Decoração", "Consultoria", "Reforma decorativa", "Mobiliário"],
    searches: ["designer de interiores {city}", "decoração de interiores {city}", "decorador {city}"],
  }),
  mv({
    id: "marcenaria",
    label: "Móveis Planejados",
    keywords: ["marcenaria", "marceneiro", "moveis planejados", "móveis planejados", "armarios planejados"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "marcenaria",
    yourBusinessLabel: "Sua marcenaria",
    suggestedServices: ["Móveis planejados", "Armários", "Cozinhas", "Closets", "Home office"],
    searches: ["móveis planejados {city}", "marcenaria {city}", "marceneiro {city}"],
  }),
  mv({
    id: "serralheria",
    label: "Serralheria",
    keywords: ["serralheria", "serralheiro", "portao", "portão", "grade", "estrutura metalica"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "serralheria",
    yourBusinessLabel: "Sua serralheria",
    suggestedServices: ["Portões", "Grades", "Estruturas metálicas", "Corrimãos", "Coberturas"],
    searches: ["serralheria {city}", "serralheiro {city}", "portão automático {city}"],
  }),
  mv({
    id: "gesso-drywall",
    label: "Gesso e Drywall",
    keywords: ["gesso", "drywall", "forro de gesso", "sancas", "divisoria drywall", "divisória drywall"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Forro de gesso", "Drywall", "Sancas", "Paredes", "Rebaixamento"],
    searches: ["gesso {city}", "drywall {city}", "forro de gesso {city}"],
  }),
  mv({
    id: "esquadrias",
    label: "Esquadrias",
    keywords: ["esquadrias", "janelas de aluminio", "janelas de alumínio", "portas de aluminio", "portas de alumínio", "pvc"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Janelas de alumínio", "Portas", "Esquadrias de PVC", "Box", "Instalação"],
    searches: ["esquadrias {city}", "janelas de alumínio {city}", "esquadrias de PVC {city}"],
  }),
  mv({
    id: "impermeabilizacao",
    label: "Impermeabilização",
    keywords: ["impermeabilizacao", "impermeabilização", "infiltracao", "infiltração", "laje", "telhado infiltração"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Impermeabilização de laje", "Telhado", "Piscina", "Banheiro", "Infiltração"],
    searches: ["impermeabilização {city}", "impermeabilização de laje {city}", "infiltração {city}"],
  }),
  mv({
    id: "limpeza-pos-obra",
    label: "Limpeza Pós-Obra",
    keywords: ["limpeza pos obra", "limpeza pós-obra", "limpeza de obra", "limpeza pesada", "limpeza fina"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Limpeza pós-obra", "Limpeza fina", "Limpeza pesada", "Remoção de entulho", "Higienização"],
    searches: ["limpeza pós-obra {city}", "limpeza de obra {city}", "limpeza pós-obra perto de mim"],
  }),
  mv({
    id: "telhados",
    label: "Telhados",
    keywords: ["telhado", "telhados", "telhador", "cobertura", "reforma de telhado", "telha"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Reforma de telhado", "Instalação", "Manutenção", "Cobertura metálica", "Calhas"],
    searches: ["telhado {city}", "reforma de telhado {city}", "telhador {city}"],
  }),
  mv({
    id: "calhas",
    label: "Calhas",
    keywords: ["calhas", "calha", "rufo", "condutor pluvial", "calha de aluminio"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Instalação de calhas", "Manutenção", "Troca de calhas", "Rufos", "Condutores"],
    searches: ["calhas {city}", "instalação de calhas {city}", "calhas e rufos {city}"],
  }),
  mv({
    id: "piscinas",
    label: "Piscinas",
    keywords: ["piscina", "piscinas", "construcao de piscina", "construção de piscina", "manutencao de piscina", "manutenção de piscina"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Construção de piscina", "Manutenção", "Reforma", "Aquecimento", "Tratamento de água"],
    searches: ["construção de piscina {city}", "manutenção de piscina {city}", "piscina {city}"],
  }),
  mv({
    id: "energia-solar",
    label: "Energia Solar",
    keywords: ["energia solar", "solar", "fotovoltaica", "painel solar", "placa solar"],
    macroCategory: "casa",
    templateSlug: "energia-solar",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Instalação residencial", "Comercial", "Manutenção", "Simulação", "Financiamento"],
    searches: ["energia solar {city}", "painel solar {city}", "energia solar residencial {city}"],
  }),
  mv({
    id: "vidracaria",
    label: "Vidraçaria",
    keywords: ["vidracaria", "vidraçaria", "box", "espelho", "vidro temperado", "blindex"],
    macroCategory: "casa",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "vidraçaria",
    yourBusinessLabel: "Sua vidraçaria",
    suggestedServices: ["Box blindex", "Espelhos", "Vidro temperado", "Janelas", "Fachadas"],
    searches: ["vidraçaria {city}", "box blindex {city}", "vidro temperado {city}"],
  }),
  mv({
    id: "pintor",
    label: "Pintor",
    keywords: ["pintor", "pintura", "pintura residencial", "pintura apartamento", "pintura predial"],
    macroCategory: "construcao",
    templateSlug: "construcao",
    priority: "medium",
    businessType: "pintor",
    yourBusinessLabel: "Seu negócio",
    suggestedServices: ["Pintura interna", "Pintura externa", "Textura", "Grafiato", "Impermeabilização"],
    searches: ["pintor {city}", "pintura apartamento {city}", "pintor perto de mim"],
  }),

  // ══════════════════════════════════════════════════════════════
  // SERVIÇOS LOCAIS
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "limpeza-residencial",
    label: "Limpeza Residencial",
    keywords: ["limpeza residencial", "faxina", "diarista", "empregada domestica", "empregada doméstica", "limpeza de casa"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "high",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Limpeza residencial", "Faxina", "Diarista", "Limpeza semanal", "Limpeza pós-festa"],
    searches: ["limpeza residencial {city}", "diarista {city}", "faxina {city}"],
  }),
  mv({
    id: "limpeza-comercial",
    label: "Limpeza Comercial",
    keywords: ["limpeza comercial", "limpeza predial", "limpeza de escritorio", "limpeza de escritório", "terceirizacao de limpeza"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Limpeza comercial", "Limpeza predial", "Escritórios", "Condomínios", "Contrato mensal"],
    searches: ["limpeza comercial {city}", "limpeza predial {city}", "empresa de limpeza {city}"],
  }),
  mv({
    id: "seguranca-eletronica",
    label: "Segurança Eletrônica",
    keywords: ["seguranca eletronica", "segurança eletrônica", "alarme", "cerca eletrica", "cerca elétrica", "portao automatico"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Alarme", "Cerca elétrica", "Portão automático", "Interfone", "Central de monitoramento"],
    searches: ["segurança eletrônica {city}", "alarme residencial {city}", "cerca elétrica {city}"],
  }),
  mv({
    id: "monitoramento",
    label: "Monitoramento",
    keywords: ["monitoramento", "central de monitoramento", "monitoramento 24h", "empresa de monitoramento"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Monitoramento 24h", "Central de alarme", "Ronda", "Resposta a alarme", "Videomonitoramento"],
    searches: ["monitoramento {city}", "central de monitoramento {city}", "monitoramento 24 horas {city}"],
  }),
  mv({
    id: "instalacao-cameras",
    label: "Instalação de Câmeras",
    keywords: ["instalacao de cameras", "instalação de câmeras", "camera de seguranca", "câmera de segurança", "cctv", "cftv"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Câmeras de segurança", "CFTV", "DVR/NVR", "Instalação", "Manutenção"],
    searches: ["instalação de câmeras {city}", "câmera de segurança {city}", "CFTV {city}"],
  }),
  mv({
    id: "ar-condicionado",
    label: "Ar Condicionado",
    keywords: ["ar condicionado", "ar-condicionado", "instalacao de ar", "instalação de ar", "manutencao de ar", "climatizacao"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "high",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Instalação", "Manutenção", "Limpeza", "Higienização", "Venda de equipamentos"],
    searches: ["ar condicionado {city}", "instalação ar condicionado {city}", "manutenção ar condicionado {city}"],
  }),
  mv({
    id: "assistencia-tecnica",
    label: "Assistência Técnica",
    keywords: ["assistencia tecnica", "assistência técnica", "conserto", "reparo", "manutencao", "manutenção"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "assistência",
    yourBusinessLabel: "Sua assistência",
    suggestedServices: ["Conserto", "Manutenção", "Peças", "Garantia", "Atendimento domiciliar"],
    searches: ["assistência técnica {city}", "conserto {city}", "assistência técnica perto de mim"],
  }),
  mv({
    id: "dedetizacao",
    label: "Controle de Pragas",
    keywords: ["dedetizacao", "dedetização", "pragas", "cupim", "desinsetizacao", "desinsetização", "dedetizadora", "controle de pragas"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Dedetização", "Descupinização", "Controle de pragas", "Desratização", "Preventivo"],
    searches: ["dedetização {city}", "dedetizadora {city}", "controle de pragas {city}"],
  }),
  mv({
    id: "jardinagem",
    label: "Jardinagem",
    keywords: ["jardinagem", "jardineiro", "paisagismo", "jardim", "grama", "podas"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Jardinagem", "Paisagismo", "Poda de árvores", "Manutenção de jardim", "Irrigação"],
    searches: ["jardinagem {city}", "jardineiro {city}", "paisagismo {city}"],
  }),
  mv({
    id: "transporte-executivo",
    label: "Transporte Executivo",
    keywords: ["transporte executivo", "motorista particular", "transfer", "van executiva", "carro com motorista"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Transfer aeroporto", "Transporte executivo", "Motorista particular", "Viagens corporativas", "Eventos"],
    searches: ["transporte executivo {city}", "motorista particular {city}", "transfer aeroporto {city}"],
  }),
  mv({
    id: "desentupidora",
    label: "Desentupidora",
    keywords: ["desentupidora", "desentupimento", "entupido", "esgoto", "hidrojateamento"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Desentupimento", "Limpeza de caixa", "Hidrojateamento", "Vídeo inspeção", "24 horas"],
    searches: ["desentupidora {city}", "desentupidora 24 horas {city}", "desentupimento {city}"],
  }),
  mv({
    id: "eletricista",
    label: "Eletricista",
    keywords: ["eletricista", "eletrica", "elétrica", "instalacao eletrica", "instalação elétrica"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "negócio",
    yourBusinessLabel: "Seu negócio",
    suggestedServices: ["Instalação", "Manutenção", "Emergência 24h", "Quadro elétrico", "Iluminação"],
    searches: ["eletricista {city}", "eletricista 24 horas {city}", "eletricista perto de mim"],
  }),
  mv({
    id: "encanador",
    label: "Encanador",
    keywords: ["encanador", "hidraulica", "hidráulica", "vazamento", "bombeiro hidraulico"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "negócio",
    yourBusinessLabel: "Seu negócio",
    suggestedServices: ["Vazamentos", "Instalação", "Manutenção", "Emergência", "Caixa d'água"],
    searches: ["encanador {city}", "encanador perto de mim", "encanador 24 horas {city}"],
  }),
  mv({
    id: "chaveiro",
    label: "Chaveiro",
    keywords: ["chaveiro", "chave", "fechadura", "abrir porta", "copia de chave"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "negócio",
    yourBusinessLabel: "Seu negócio",
    suggestedServices: ["Abertura de portas", "Cópia de chaves", "Troca de fechadura", "Fechadura digital", "24 horas"],
    searches: ["chaveiro {city}", "chaveiro 24 horas {city}", "chaveiro perto de mim"],
  }),
  mv({
    id: "guincho",
    label: "Guincho",
    keywords: ["guincho", "reboque", "socorro mecanico", "socorro mecânico", "pane seca"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "guincho",
    yourBusinessLabel: "Seu guincho",
    suggestedServices: ["Guincho 24h", "Reboque", "Socorro mecânico", "Pane seca", "Transporte de veículos"],
    searches: ["guincho {city}", "guincho 24 horas {city}", "reboque {city}"],
  }),
  mv({
    id: "mudancas",
    label: "Mudanças",
    keywords: ["mudanca", "mudança", "mudancas", "mudanças", "carreto", "frete", "empresa de mudanca"],
    macroCategory: "servicos",
    templateSlug: "servicos-locais",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Mudança residencial", "Mudança comercial", "Carreto", "Embalagem", "Montagem"],
    searches: ["mudanças {city}", "empresa de mudança {city}", "carreto {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // EDUCAÇÃO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "escola-idiomas",
    label: "Escola de Idiomas",
    keywords: ["escola de ingles", "escola de inglês", "curso de ingles", "curso de inglês", "idiomas", "escola de idiomas"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "medium",
    businessType: "escola",
    yourBusinessLabel: "Sua escola",
    suggestedServices: ["Inglês", "Espanhol", "Aulas particulares", "Preparatório", "Intensivo"],
    searches: ["escola de inglês {city}", "curso de inglês {city}", "escola de idiomas {city}"],
  }),
  mv({
    id: "reforco-escolar",
    label: "Reforço Escolar",
    keywords: ["reforco escolar", "reforço escolar", "aula particular", "professor particular", "tutor"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "medium",
    businessType: "escola",
    yourBusinessLabel: "Sua escola",
    suggestedServices: ["Reforço escolar", "Matemática", "Português", "Aulas particulares", "Preparação para provas"],
    searches: ["reforço escolar {city}", "aula particular {city}", "professor particular {city}"],
  }),
  mv({
    id: "escola-particular",
    label: "Escola Particular",
    keywords: ["escola particular", "colegio particular", "colégio particular", "educacao infantil", "educação infantil", "ensino fundamental"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "high",
    businessType: "escola",
    yourBusinessLabel: "Sua escola",
    suggestedServices: ["Educação infantil", "Ensino fundamental", "Ensino médio", "Matrículas", "Visita guiada"],
    searches: ["escola particular {city}", "colégio particular {city}", "matrícula escola {city}"],
  }),
  mv({
    id: "cursos-profissionalizantes",
    label: "Cursos Profissionalizantes",
    keywords: ["cursos profissionalizantes", "curso profissionalizante", "qualificacao profissional", "qualificação profissional", "senac", "curso tecnico"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "medium",
    businessType: "escola",
    yourBusinessLabel: "Sua escola",
    suggestedServices: ["Cursos técnicos", "Qualificação", "Certificação", "EAD", "Estágio"],
    searches: ["cursos profissionalizantes {city}", "curso profissionalizante {city}", "qualificação profissional {city}"],
  }),
  mv({
    id: "autoescola",
    label: "Autoescola",
    keywords: ["autoescola", "auto escola", "cnh", "habilitacao", "habilitação", "aulas de direcao"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "high",
    businessType: "autoescola",
    yourBusinessLabel: "Sua autoescola",
    suggestedServices: ["CNH categoria B", "Primeira habilitação", "Reciclagem", "Aulas práticas", "Simulador"],
    searches: ["autoescola {city}", "auto escola {city}", "CNH {city}"],
  }),
  mv({
    id: "cursos-preparatorios",
    label: "Cursos Preparatórios",
    keywords: ["cursos preparatorios", "cursos preparatórios", "pre vestibular", "pré-vestibular", "enem", "concurso publico", "concurso público"],
    macroCategory: "educacao",
    templateSlug: "educacao",
    priority: "medium",
    businessType: "escola",
    yourBusinessLabel: "Sua escola",
    suggestedServices: ["Pré-vestibular", "ENEM", "Concurso público", "Intensivo", "Redação"],
    searches: ["curso preparatório {city}", "pré-vestibular {city}", "curso ENEM {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // AUTOMOTIVO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "oficina",
    label: "Oficina Mecânica",
    keywords: ["oficina", "oficina mecanica", "oficina mecânica", "mecanica", "mecânica", "mecanico", "mecânico"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "high",
    businessType: "oficina",
    yourBusinessLabel: "Sua oficina",
    suggestedServices: ["Revisão", "Freios", "Suspensão", "Troca de óleo", "Diagnóstico"],
    searches: ["oficina mecânica {city}", "mecânico perto de mim", "oficina {city}"],
  }),
  mv({
    id: "auto-center",
    label: "Auto Center",
    keywords: ["auto center", "autocenter", "centro automotivo"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "high",
    businessType: "auto center",
    yourBusinessLabel: "Seu auto center",
    suggestedServices: ["Revisão completa", "Alinhamento", "Balanceamento", "Troca de óleo", "Freios"],
    searches: ["auto center {city}", "centro automotivo {city}", "auto center perto de mim"],
  }),
  mv({
    id: "funilaria",
    label: "Funilaria",
    keywords: ["funilaria", "funileiro", "lanternagem", "pintura automotiva", "amassado"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "funilaria",
    yourBusinessLabel: "Sua funilaria",
    suggestedServices: ["Funilaria", "Lanternagem", "Pintura automotiva", "Martelinho de ouro", "Polimento"],
    searches: ["funilaria {city}", "funileiro {city}", "lanternagem {city}"],
  }),
  mv({
    id: "martelinho-ouro",
    label: "Martelinho de Ouro",
    keywords: ["martelinho de ouro", "martelinho", "amassado sem pintura", "reparo de amassado"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "oficina",
    yourBusinessLabel: "Sua oficina",
    suggestedServices: ["Martelinho de ouro", "Reparo de amassados", "Granizo", "Polimento", "Vitrificação"],
    searches: ["martelinho de ouro {city}", "amassado sem pintura {city}", "martelinho {city}"],
  }),
  mv({
    id: "auto-eletrica",
    label: "Auto Elétrica",
    keywords: ["auto eletrica", "auto elétrica", "eletrica automotiva", "elétrica automotiva", "bateria automotiva"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "oficina",
    yourBusinessLabel: "Sua oficina",
    suggestedServices: ["Auto elétrica", "Bateria", "Alternador", "Partida", "Instalação de acessórios"],
    searches: ["auto elétrica {city}", "elétrica automotiva {city}", "bateria automotiva {city}"],
  }),
  mv({
    id: "insulfilm",
    label: "Insulfilm",
    keywords: ["insulfilm", "pelicula automotiva", "película automotiva", "pelicula para vidro", "película para vidro"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "oficina",
    yourBusinessLabel: "Sua oficina",
    suggestedServices: ["Insulfilm", "Película automotiva", "Película residencial", "Antivandalismo", "Película espelhada"],
    searches: ["insulfilm {city}", "película automotiva {city}", "insulfilm perto de mim"],
  }),
  mv({
    id: "estetica-automotiva",
    label: "Estética Automotiva",
    keywords: ["estetica automotiva", "estética automotiva", "detailing", "polimento automotivo", "vitrificacao", "vitrificação"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "high",
    businessType: "estética automotiva",
    yourBusinessLabel: "Sua estética automotiva",
    suggestedServices: ["Detailing", "Polimento", "Vitrificação", "Higienização interna", "Cristalização"],
    searches: ["estética automotiva {city}", "detailing {city}", "polimento automotivo {city}"],
  }),
  mv({
    id: "lava-rapido",
    label: "Lava Rápido",
    keywords: ["lava rapido", "lava rápido", "lavagem automotiva", "lavagem de carro"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "lava rápido",
    yourBusinessLabel: "Seu lava rápido",
    suggestedServices: ["Lavagem simples", "Lavagem completa", "Polimento", "Higienização", "Cera"],
    searches: ["lava rápido {city}", "lavagem automotiva {city}", "lava rápido perto de mim"],
  }),
  mv({
    id: "rastreador-veicular",
    label: "Rastreador Veicular",
    keywords: ["rastreador", "rastreador veicular", "rastreamento", "bloqueador", "gps veicular"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "empresa",
    yourBusinessLabel: "Sua empresa",
    suggestedServices: ["Rastreador veicular", "Bloqueador", "Monitoramento 24h", "Instalação", "Manutenção"],
    searches: ["rastreador veicular {city}", "rastreamento veicular {city}", "rastreador {city}"],
  }),
  mv({
    id: "locadora-veiculos",
    label: "Locadora de Veículos",
    keywords: ["locadora", "locadora de veiculos", "locadora de veículos", "aluguel de carro", "rent a car"],
    macroCategory: "automotivo",
    templateSlug: "automotivo",
    priority: "medium",
    businessType: "locadora",
    yourBusinessLabel: "Sua locadora",
    suggestedServices: ["Aluguel de carros", "Locação mensal", "Frota corporativa", "SUV", "Veículos executivos"],
    searches: ["locadora de veículos {city}", "aluguel de carro {city}", "rent a car {city}"],
  }),

  // ══════════════════════════════════════════════════════════════
  // ALIMENTAÇÃO
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "restaurante",
    label: "Restaurante",
    keywords: ["restaurante", "comida", "almoco", "almoço", "jantar"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "high",
    businessType: "restaurante",
    yourBusinessLabel: "Seu restaurante",
    suggestedServices: ["Almoço", "Jantar", "Delivery", "Reservas", "Cardápio executivo"],
    searches: ["restaurante {city}", "restaurante perto de mim", "melhor restaurante {city}"],
  }),
  mv({
    id: "hamburgueria",
    label: "Hamburgueria",
    keywords: ["hamburgueria", "hamburguer", "hambúrguer", "burger", "smash burger"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "high",
    businessType: "hamburgueria",
    yourBusinessLabel: "Sua hamburgueria",
    suggestedServices: ["Hambúrguer artesanal", "Delivery", "Combo", "Smash burger", "Porções"],
    searches: ["hamburgueria {city}", "hambúrguer {city}", "hamburgueria delivery {city}"],
  }),
  mv({
    id: "sushi",
    label: "Sushi",
    keywords: ["sushi", "japones", "japonês", "temaki", "restaurante japones", "restaurante japonês"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "medium",
    businessType: "restaurante",
    yourBusinessLabel: "Seu restaurante",
    suggestedServices: ["Rodízio", "Delivery", "Combinados", "Temaki", "Sashimi"],
    searches: ["sushi {city}", "restaurante japonês {city}", "sushi delivery {city}"],
  }),
  mv({
    id: "marmitaria",
    label: "Marmitaria",
    keywords: ["marmitaria", "marmita", "marmitex", "comida caseira", "quentinha"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "high",
    businessType: "marmitaria",
    yourBusinessLabel: "Sua marmitaria",
    suggestedServices: ["Marmita", "Delivery", "Cardápio semanal", "Marmita fitness", "Encomendas"],
    searches: ["marmitaria {city}", "marmita {city}", "marmitaria delivery {city}"],
  }),
  mv({
    id: "delivery",
    label: "Delivery",
    keywords: ["delivery", "entrega de comida", "ifood", "comida delivery", "pedido online"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "medium",
    businessType: "delivery",
    yourBusinessLabel: "Seu delivery",
    suggestedServices: ["Delivery", "Pedido online", "Entrega rápida", "Promoções", "Cardápio digital"],
    searches: ["delivery {city}", "comida delivery {city}", "entrega de comida {city}"],
  }),
  mv({
    id: "confeitaria",
    label: "Confeitaria",
    keywords: ["confeitaria", "confeiteiro", "confeiteira", "bolo", "doces", "doceria"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "medium",
    businessType: "confeitaria",
    yourBusinessLabel: "Sua confeitaria",
    suggestedServices: ["Bolos", "Doces finos", "Encomendas", "Festa infantil", "Delivery"],
    searches: ["confeitaria {city}", "bolo {city}", "doces {city}"],
  }),
  mv({
    id: "padaria",
    label: "Padaria",
    keywords: ["padaria", "pao", "pão", "confeitaria de bairro", "bakery"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "high",
    businessType: "padaria",
    yourBusinessLabel: "Sua padaria",
    suggestedServices: ["Pães artesanais", "Café da manhã", "Salgados", "Bolos", "Delivery"],
    searches: ["padaria {city}", "padaria perto de mim", "pão artesanal {city}"],
  }),
  mv({
    id: "buffet",
    label: "Buffet",
    keywords: ["buffet", "buffet para festa", "buffet infantil", "eventos", "casamento buffet"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "medium",
    businessType: "buffet",
    yourBusinessLabel: "Seu buffet",
    suggestedServices: ["Buffet para festas", "Casamentos", "Corporativo", "Infantil", "Coffee break"],
    searches: ["buffet {city}", "buffet para festa {city}", "buffet infantil {city}"],
  }),
  mv({
    id: "churrascaria",
    label: "Churrascaria",
    keywords: ["churrascaria", "churrasco", "rodizio", "rodízio", "espeto"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "medium",
    businessType: "churrascaria",
    yourBusinessLabel: "Sua churrascaria",
    suggestedServices: ["Rodízio", "Almoço", "Eventos", "Delivery", "Espeto corrido"],
    searches: ["churrascaria {city}", "churrasco {city}", "rodízio {city}"],
  }),
  mv({
    id: "pizzaria",
    label: "Pizzaria",
    keywords: ["pizzaria", "pizza", "pizzaria delivery", "pizza artesanal"],
    macroCategory: "alimentacao",
    templateSlug: "alimentacao",
    priority: "high",
    businessType: "pizzaria",
    yourBusinessLabel: "Sua pizzaria",
    suggestedServices: ["Delivery", "Rodízio", "Pizza artesanal", "Promoções", "Borda recheada"],
    searches: ["pizzaria {city}", "pizza delivery {city}", "pizzaria perto de mim"],
  }),

  // ══════════════════════════════════════════════════════════════
  // OUTROS
  // ══════════════════════════════════════════════════════════════
  mv({
    id: "academia",
    label: "Academia",
    keywords: ["academia", "musculacao", "musculação", "crossfit", "personal trainer", "personal", "fitness"],
    macroCategory: "geral",
    templateSlug: "outro",
    priority: "high",
    businessType: "academia",
    yourBusinessLabel: "Sua academia",
    suggestedServices: ["Musculação", "Personal trainer", "Aulas em grupo", "Avaliação física", "Crossfit"],
    searches: ["academia {city}", "academia perto de mim", "personal trainer {city}"],
  }),
];
