/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as ProgramaDeCrescimentoRouteImport } from './routes/programa-de-crescimento'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as SegmentRouteImport } from './routes/$segment'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SolucoesProducaoDeConteudoRouteImport } from './routes/solucoes/producao-de-conteudo'
import { Route as SolucoesMetaAdsRouteImport } from './routes/solucoes/meta-ads'
import { Route as SolucoesLandingPagesRouteImport } from './routes/solucoes/landing-pages'
import { Route as SolucoesGoogleAdsRouteImport } from './routes/solucoes/google-ads'
import { Route as ProjetosPousadaRouteImport } from './routes/projetos/pousada'
import { Route as ProjetosNobreRouteImport } from './routes/projetos/nobre'
import { Route as CasesSlugRouteImport } from './routes/cases/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as PlaygroundCasesDecisionLanguageRouteImport } from './routes/playground/cases/decision-language'
import { Route as BlogCategoriaCategoryRouteImport } from './routes/blog/categoria/$category'
import { Route as AdminExecucaoReferenciaRouteImport } from './routes/admin/execucao/referencia'
import { Route as AdminExecucaoProducaoRouteImport } from './routes/admin/execucao/producao'
import { Route as AdminExecucaoPlanejamentoRouteImport } from './routes/admin/execucao/planejamento'
import { Route as AdminExecucaoHojeRouteImport } from './routes/admin/execucao/hoje'
import { Route as AdminExecucaoClientesRouteImport } from './routes/admin/execucao/clientes'
import { Route as AdminExecucaoCapacidadeRouteImport } from './routes/admin/execucao/capacidade'
import { Route as AdminExecucaoRituaisIndexRouteImport } from './routes/admin/execucao/rituais/index'
import { Route as AdminExecucaoRituaisReviewRouteImport } from './routes/admin/execucao/rituais/review'
import { Route as AdminExecucaoRituaisPlanningRouteImport } from './routes/admin/execucao/rituais/planning'
import { Route as AdminExecucaoRituaisCheckinRouteImport } from './routes/admin/execucao/rituais/checkin'

const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaDeCrescimentoRoute = ProgramaDeCrescimentoRouteImport.update({
  id: '/programa-de-crescimento',
  path: '/programa-de-crescimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentRoute = SegmentRouteImport.update({
  id: '/$segment',
  path: '/$segment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SolucoesProducaoDeConteudoRoute =
  SolucoesProducaoDeConteudoRouteImport.update({
    id: '/solucoes/producao-de-conteudo',
    path: '/solucoes/producao-de-conteudo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesMetaAdsRoute = SolucoesMetaAdsRouteImport.update({
  id: '/solucoes/meta-ads',
  path: '/solucoes/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesLandingPagesRoute = SolucoesLandingPagesRouteImport.update({
  id: '/solucoes/landing-pages',
  path: '/solucoes/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesGoogleAdsRoute = SolucoesGoogleAdsRouteImport.update({
  id: '/solucoes/google-ads',
  path: '/solucoes/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosPousadaRoute = ProjetosPousadaRouteImport.update({
  id: '/projetos/pousada',
  path: '/projetos/pousada',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNobreRoute = ProjetosNobreRouteImport.update({
  id: '/projetos/nobre',
  path: '/projetos/nobre',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PlaygroundCasesDecisionLanguageRoute =
  PlaygroundCasesDecisionLanguageRouteImport.update({
    id: '/playground/cases/decision-language',
    path: '/playground/cases/decision-language',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategoriaCategoryRoute = BlogCategoriaCategoryRouteImport.update({
  id: '/blog/categoria/$category',
  path: '/blog/categoria/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExecucaoReferenciaRoute = AdminExecucaoReferenciaRouteImport.update({
  id: '/execucao/referencia',
  path: '/execucao/referencia',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExecucaoProducaoRoute = AdminExecucaoProducaoRouteImport.update({
  id: '/execucao/producao',
  path: '/execucao/producao',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExecucaoPlanejamentoRoute =
  AdminExecucaoPlanejamentoRouteImport.update({
    id: '/execucao/planejamento',
    path: '/execucao/planejamento',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExecucaoHojeRoute = AdminExecucaoHojeRouteImport.update({
  id: '/execucao/hoje',
  path: '/execucao/hoje',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExecucaoClientesRoute = AdminExecucaoClientesRouteImport.update({
  id: '/execucao/clientes',
  path: '/execucao/clientes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExecucaoCapacidadeRoute = AdminExecucaoCapacidadeRouteImport.update({
  id: '/execucao/capacidade',
  path: '/execucao/capacidade',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExecucaoRituaisIndexRoute =
  AdminExecucaoRituaisIndexRouteImport.update({
    id: '/execucao/rituais/',
    path: '/execucao/rituais/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExecucaoRituaisReviewRoute =
  AdminExecucaoRituaisReviewRouteImport.update({
    id: '/execucao/rituais/review',
    path: '/execucao/rituais/review',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExecucaoRituaisPlanningRoute =
  AdminExecucaoRituaisPlanningRouteImport.update({
    id: '/execucao/rituais/planning',
    path: '/execucao/rituais/planning',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExecucaoRituaisCheckinRoute =
  AdminExecucaoRituaisCheckinRouteImport.update({
    id: '/execucao/rituais/checkin',
    path: '/execucao/rituais/checkin',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$segment': typeof SegmentRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/metodologia': typeof MetodologiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/programa-de-crescimento': typeof ProgramaDeCrescimentoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projetos/nobre': typeof ProjetosNobreRoute
  '/projetos/pousada': typeof ProjetosPousadaRoute
  '/solucoes/google-ads': typeof SolucoesGoogleAdsRoute
  '/solucoes/landing-pages': typeof SolucoesLandingPagesRoute
  '/solucoes/meta-ads': typeof SolucoesMetaAdsRoute
  '/solucoes/producao-de-conteudo': typeof SolucoesProducaoDeConteudoRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/admin/execucao/capacidade': typeof AdminExecucaoCapacidadeRoute
  '/admin/execucao/clientes': typeof AdminExecucaoClientesRoute
  '/admin/execucao/hoje': typeof AdminExecucaoHojeRoute
  '/admin/execucao/planejamento': typeof AdminExecucaoPlanejamentoRoute
  '/admin/execucao/producao': typeof AdminExecucaoProducaoRoute
  '/admin/execucao/referencia': typeof AdminExecucaoReferenciaRoute
  '/blog/categoria/$category': typeof BlogCategoriaCategoryRoute
  '/playground/cases/decision-language': typeof PlaygroundCasesDecisionLanguageRoute
  '/admin/execucao/rituais/checkin': typeof AdminExecucaoRituaisCheckinRoute
  '/admin/execucao/rituais/planning': typeof AdminExecucaoRituaisPlanningRoute
  '/admin/execucao/rituais/review': typeof AdminExecucaoRituaisReviewRoute
  '/admin/execucao/rituais/': typeof AdminExecucaoRituaisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$segment': typeof SegmentRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/metodologia': typeof MetodologiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/programa-de-crescimento': typeof ProgramaDeCrescimentoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projetos/nobre': typeof ProjetosNobreRoute
  '/projetos/pousada': typeof ProjetosPousadaRoute
  '/solucoes/google-ads': typeof SolucoesGoogleAdsRoute
  '/solucoes/landing-pages': typeof SolucoesLandingPagesRoute
  '/solucoes/meta-ads': typeof SolucoesMetaAdsRoute
  '/solucoes/producao-de-conteudo': typeof SolucoesProducaoDeConteudoRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cases': typeof CasesIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/admin/execucao/capacidade': typeof AdminExecucaoCapacidadeRoute
  '/admin/execucao/clientes': typeof AdminExecucaoClientesRoute
  '/admin/execucao/hoje': typeof AdminExecucaoHojeRoute
  '/admin/execucao/planejamento': typeof AdminExecucaoPlanejamentoRoute
  '/admin/execucao/producao': typeof AdminExecucaoProducaoRoute
  '/admin/execucao/referencia': typeof AdminExecucaoReferenciaRoute
  '/blog/categoria/$category': typeof BlogCategoriaCategoryRoute
  '/playground/cases/decision-language': typeof PlaygroundCasesDecisionLanguageRoute
  '/admin/execucao/rituais/checkin': typeof AdminExecucaoRituaisCheckinRoute
  '/admin/execucao/rituais/planning': typeof AdminExecucaoRituaisPlanningRoute
  '/admin/execucao/rituais/review': typeof AdminExecucaoRituaisReviewRoute
  '/admin/execucao/rituais': typeof AdminExecucaoRituaisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$segment': typeof SegmentRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/metodologia': typeof MetodologiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/programa-de-crescimento': typeof ProgramaDeCrescimentoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projetos/nobre': typeof ProjetosNobreRoute
  '/projetos/pousada': typeof ProjetosPousadaRoute
  '/solucoes/google-ads': typeof SolucoesGoogleAdsRoute
  '/solucoes/landing-pages': typeof SolucoesLandingPagesRoute
  '/solucoes/meta-ads': typeof SolucoesMetaAdsRoute
  '/solucoes/producao-de-conteudo': typeof SolucoesProducaoDeConteudoRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/admin/execucao/capacidade': typeof AdminExecucaoCapacidadeRoute
  '/admin/execucao/clientes': typeof AdminExecucaoClientesRoute
  '/admin/execucao/hoje': typeof AdminExecucaoHojeRoute
  '/admin/execucao/planejamento': typeof AdminExecucaoPlanejamentoRoute
  '/admin/execucao/producao': typeof AdminExecucaoProducaoRoute
  '/admin/execucao/referencia': typeof AdminExecucaoReferenciaRoute
  '/blog/categoria/$category': typeof BlogCategoriaCategoryRoute
  '/playground/cases/decision-language': typeof PlaygroundCasesDecisionLanguageRoute
  '/admin/execucao/rituais/checkin': typeof AdminExecucaoRituaisCheckinRoute
  '/admin/execucao/rituais/planning': typeof AdminExecucaoRituaisPlanningRoute
  '/admin/execucao/rituais/review': typeof AdminExecucaoRituaisReviewRoute
  '/admin/execucao/rituais/': typeof AdminExecucaoRituaisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$segment'
    | '/diagnostico'
    | '/metodologia'
    | '/obrigado'
    | '/programa-de-crescimento'
    | '/tecnologia'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/projetos/nobre'
    | '/projetos/pousada'
    | '/solucoes/google-ads'
    | '/solucoes/landing-pages'
    | '/solucoes/meta-ads'
    | '/solucoes/producao-de-conteudo'
    | '/admin/'
    | '/blog/'
    | '/cases/'
    | '/solucoes/'
    | '/admin/execucao/capacidade'
    | '/admin/execucao/clientes'
    | '/admin/execucao/hoje'
    | '/admin/execucao/planejamento'
    | '/admin/execucao/producao'
    | '/admin/execucao/referencia'
    | '/blog/categoria/$category'
    | '/playground/cases/decision-language'
    | '/admin/execucao/rituais/checkin'
    | '/admin/execucao/rituais/planning'
    | '/admin/execucao/rituais/review'
    | '/admin/execucao/rituais/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$segment'
    | '/diagnostico'
    | '/metodologia'
    | '/obrigado'
    | '/programa-de-crescimento'
    | '/tecnologia'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/projetos/nobre'
    | '/projetos/pousada'
    | '/solucoes/google-ads'
    | '/solucoes/landing-pages'
    | '/solucoes/meta-ads'
    | '/solucoes/producao-de-conteudo'
    | '/admin'
    | '/blog'
    | '/cases'
    | '/solucoes'
    | '/admin/execucao/capacidade'
    | '/admin/execucao/clientes'
    | '/admin/execucao/hoje'
    | '/admin/execucao/planejamento'
    | '/admin/execucao/producao'
    | '/admin/execucao/referencia'
    | '/blog/categoria/$category'
    | '/playground/cases/decision-language'
    | '/admin/execucao/rituais/checkin'
    | '/admin/execucao/rituais/planning'
    | '/admin/execucao/rituais/review'
    | '/admin/execucao/rituais'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$segment'
    | '/diagnostico'
    | '/metodologia'
    | '/obrigado'
    | '/programa-de-crescimento'
    | '/tecnologia'
    | '/admin/leads'
    | '/admin/login'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/projetos/nobre'
    | '/projetos/pousada'
    | '/solucoes/google-ads'
    | '/solucoes/landing-pages'
    | '/solucoes/meta-ads'
    | '/solucoes/producao-de-conteudo'
    | '/admin/'
    | '/blog/'
    | '/cases/'
    | '/solucoes/'
    | '/admin/execucao/capacidade'
    | '/admin/execucao/clientes'
    | '/admin/execucao/hoje'
    | '/admin/execucao/planejamento'
    | '/admin/execucao/producao'
    | '/admin/execucao/referencia'
    | '/blog/categoria/$category'
    | '/playground/cases/decision-language'
    | '/admin/execucao/rituais/checkin'
    | '/admin/execucao/rituais/planning'
    | '/admin/execucao/rituais/review'
    | '/admin/execucao/rituais/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SegmentRoute: typeof SegmentRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ProgramaDeCrescimentoRoute: typeof ProgramaDeCrescimentoRoute
  TecnologiaRoute: typeof TecnologiaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CasesSlugRoute: typeof CasesSlugRoute
  ProjetosNobreRoute: typeof ProjetosNobreRoute
  ProjetosPousadaRoute: typeof ProjetosPousadaRoute
  SolucoesGoogleAdsRoute: typeof SolucoesGoogleAdsRoute
  SolucoesLandingPagesRoute: typeof SolucoesLandingPagesRoute
  SolucoesMetaAdsRoute: typeof SolucoesMetaAdsRoute
  SolucoesProducaoDeConteudoRoute: typeof SolucoesProducaoDeConteudoRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
  BlogCategoriaCategoryRoute: typeof BlogCategoriaCategoryRoute
  PlaygroundCasesDecisionLanguageRoute: typeof PlaygroundCasesDecisionLanguageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-crescimento': {
      id: '/programa-de-crescimento'
      path: '/programa-de-crescimento'
      fullPath: '/programa-de-crescimento'
      preLoaderRoute: typeof ProgramaDeCrescimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$segment': {
      id: '/$segment'
      path: '/$segment'
      fullPath: '/$segment'
      preLoaderRoute: typeof SegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/solucoes/producao-de-conteudo': {
      id: '/solucoes/producao-de-conteudo'
      path: '/solucoes/producao-de-conteudo'
      fullPath: '/solucoes/producao-de-conteudo'
      preLoaderRoute: typeof SolucoesProducaoDeConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/meta-ads': {
      id: '/solucoes/meta-ads'
      path: '/solucoes/meta-ads'
      fullPath: '/solucoes/meta-ads'
      preLoaderRoute: typeof SolucoesMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/landing-pages': {
      id: '/solucoes/landing-pages'
      path: '/solucoes/landing-pages'
      fullPath: '/solucoes/landing-pages'
      preLoaderRoute: typeof SolucoesLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/google-ads': {
      id: '/solucoes/google-ads'
      path: '/solucoes/google-ads'
      fullPath: '/solucoes/google-ads'
      preLoaderRoute: typeof SolucoesGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/pousada': {
      id: '/projetos/pousada'
      path: '/projetos/pousada'
      fullPath: '/projetos/pousada'
      preLoaderRoute: typeof ProjetosPousadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/nobre': {
      id: '/projetos/nobre'
      path: '/projetos/nobre'
      fullPath: '/projetos/nobre'
      preLoaderRoute: typeof ProjetosNobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/playground/cases/decision-language': {
      id: '/playground/cases/decision-language'
      path: '/playground/cases/decision-language'
      fullPath: '/playground/cases/decision-language'
      preLoaderRoute: typeof PlaygroundCasesDecisionLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categoria/$category': {
      id: '/blog/categoria/$category'
      path: '/blog/categoria/$category'
      fullPath: '/blog/categoria/$category'
      preLoaderRoute: typeof BlogCategoriaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/execucao/referencia': {
      id: '/admin/execucao/referencia'
      path: '/execucao/referencia'
      fullPath: '/admin/execucao/referencia'
      preLoaderRoute: typeof AdminExecucaoReferenciaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/producao': {
      id: '/admin/execucao/producao'
      path: '/execucao/producao'
      fullPath: '/admin/execucao/producao'
      preLoaderRoute: typeof AdminExecucaoProducaoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/planejamento': {
      id: '/admin/execucao/planejamento'
      path: '/execucao/planejamento'
      fullPath: '/admin/execucao/planejamento'
      preLoaderRoute: typeof AdminExecucaoPlanejamentoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/hoje': {
      id: '/admin/execucao/hoje'
      path: '/execucao/hoje'
      fullPath: '/admin/execucao/hoje'
      preLoaderRoute: typeof AdminExecucaoHojeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/clientes': {
      id: '/admin/execucao/clientes'
      path: '/execucao/clientes'
      fullPath: '/admin/execucao/clientes'
      preLoaderRoute: typeof AdminExecucaoClientesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/capacidade': {
      id: '/admin/execucao/capacidade'
      path: '/execucao/capacidade'
      fullPath: '/admin/execucao/capacidade'
      preLoaderRoute: typeof AdminExecucaoCapacidadeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/rituais/': {
      id: '/admin/execucao/rituais/'
      path: '/execucao/rituais'
      fullPath: '/admin/execucao/rituais/'
      preLoaderRoute: typeof AdminExecucaoRituaisIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/rituais/review': {
      id: '/admin/execucao/rituais/review'
      path: '/execucao/rituais/review'
      fullPath: '/admin/execucao/rituais/review'
      preLoaderRoute: typeof AdminExecucaoRituaisReviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/rituais/planning': {
      id: '/admin/execucao/rituais/planning'
      path: '/execucao/rituais/planning'
      fullPath: '/admin/execucao/rituais/planning'
      preLoaderRoute: typeof AdminExecucaoRituaisPlanningRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/execucao/rituais/checkin': {
      id: '/admin/execucao/rituais/checkin'
      path: '/execucao/rituais/checkin'
      fullPath: '/admin/execucao/rituais/checkin'
      preLoaderRoute: typeof AdminExecucaoRituaisCheckinRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExecucaoCapacidadeRoute: typeof AdminExecucaoCapacidadeRoute
  AdminExecucaoClientesRoute: typeof AdminExecucaoClientesRoute
  AdminExecucaoHojeRoute: typeof AdminExecucaoHojeRoute
  AdminExecucaoPlanejamentoRoute: typeof AdminExecucaoPlanejamentoRoute
  AdminExecucaoProducaoRoute: typeof AdminExecucaoProducaoRoute
  AdminExecucaoReferenciaRoute: typeof AdminExecucaoReferenciaRoute
  AdminExecucaoRituaisCheckinRoute: typeof AdminExecucaoRituaisCheckinRoute
  AdminExecucaoRituaisPlanningRoute: typeof AdminExecucaoRituaisPlanningRoute
  AdminExecucaoRituaisReviewRoute: typeof AdminExecucaoRituaisReviewRoute
  AdminExecucaoRituaisIndexRoute: typeof AdminExecucaoRituaisIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExecucaoCapacidadeRoute: AdminExecucaoCapacidadeRoute,
  AdminExecucaoClientesRoute: AdminExecucaoClientesRoute,
  AdminExecucaoHojeRoute: AdminExecucaoHojeRoute,
  AdminExecucaoPlanejamentoRoute: AdminExecucaoPlanejamentoRoute,
  AdminExecucaoProducaoRoute: AdminExecucaoProducaoRoute,
  AdminExecucaoReferenciaRoute: AdminExecucaoReferenciaRoute,
  AdminExecucaoRituaisCheckinRoute: AdminExecucaoRituaisCheckinRoute,
  AdminExecucaoRituaisPlanningRoute: AdminExecucaoRituaisPlanningRoute,
  AdminExecucaoRituaisReviewRoute: AdminExecucaoRituaisReviewRoute,
  AdminExecucaoRituaisIndexRoute: AdminExecucaoRituaisIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SegmentRoute: SegmentRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  MetodologiaRoute: MetodologiaRoute,
  ObrigadoRoute: ObrigadoRoute,
  ProgramaDeCrescimentoRoute: ProgramaDeCrescimentoRoute,
  TecnologiaRoute: TecnologiaRoute,
  BlogSlugRoute: BlogSlugRoute,
  CasesSlugRoute: CasesSlugRoute,
  ProjetosNobreRoute: ProjetosNobreRoute,
  ProjetosPousadaRoute: ProjetosPousadaRoute,
  SolucoesGoogleAdsRoute: SolucoesGoogleAdsRoute,
  SolucoesLandingPagesRoute: SolucoesLandingPagesRoute,
  SolucoesMetaAdsRoute: SolucoesMetaAdsRoute,
  SolucoesProducaoDeConteudoRoute: SolucoesProducaoDeConteudoRoute,
  BlogIndexRoute: BlogIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
  BlogCategoriaCategoryRoute: BlogCategoriaCategoryRoute,
  PlaygroundCasesDecisionLanguageRoute: PlaygroundCasesDecisionLanguageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
